import { CONFIG } from './config.js';

//音乐根路径
export const FILE_MUSIC_ROOT = './music/';

// type 分类  （轻音乐，伤感，）

// musicPath: FILE_MUSIC_ROOT + song_path + song_file,  ./music/jingdian/我的歌声里.mp3

// musicList1
const TYPE_1 = "天籁之音"
const FILE_MUSIC_TIANLANZHIYIN = 'tianlaizhiyin/'

// musicList2
const TYPE_2 = "轻音乐"
const FILE_MUSIC_QINGYINYUE = 'qingyinyue/'

// musicList3
const TYPE_3 = "emo"
const FILE_MUSIC_EMO = 'emo/'


// musicList4
const TYPE_4 = "经典"
const FILE_MUSIC_JINGDIAN = 'jingdian/'

// musicList5
const TYPE_5 = "气势 BGM"
const FILE_MUSIC_BGM = 'bgm/'

// musicList6
const TYPE_6 = "律动"
const FILE_MUSIC_lvdong = 'lvdong/'


// musicList7
const TYPE_7 = "动画片"
const FILE_MUSIC_donghuapian = 'donghuapian/'

// musicList8
const TYPE_8 = "民谣"
const FILE_MUSIC_minyao = 'minyao/'


//天籁之音
const musicList1 = [
  {
    song_type: TYPE_1,
    song_path: FILE_MUSIC_TIANLANZHIYIN,
    song_name: "天籁排箫 老鹰之歌 (El Condor Pasa)",
    song_file: "天籁排箫 老鹰之歌.mp3",
    img_file: "leo_rojas.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Leo Rojas",
    time: '03:36',
    des: "每次一听这深邃、高远的旋律，如雄鹰翱翔在蓝天，悠然自在，每个吹奏的音符敲击心怀，释放自己。",
  },
  {
    song_type: TYPE_1,
    song_path: FILE_MUSIC_TIANLANZHIYIN,
    song_name: "Caribbean Blue - Enya",
    song_file: "Caribbean Blue - Enya.mp3",
    img_file: "Caribbean Blue - Enya.jpg",
    lyrics_file: 'Caribbean Blue - Enya.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Enya",
    time: '03:58',
    des: "",
  },

]

//轻音乐
const musicList2 = [
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "纯净如圣诗《Idé Were Were》",
    song_file: "纯净如圣诗.mp3",
    img_file: "music_ide.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Deva Premal",
    time: '07:59',
    des: "天人合一的自然美感。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "兰花草 (天籁般的哼唱) - 卡洛儿",
    song_file: "兰花草.mp3",
    img_file: "卡洛儿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "卡洛儿",
    time: '04:19',
    des: "兰花草的香，兰花草的甜，我种兰花草，只待故人归，哪怕春去秋过冬又来。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "莫尔德颂歌 (Molde Canticle) - Sissel",
    song_file: "莫尔德颂歌.mp3",
    img_file: "莫尔德颂歌.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Sissel",
    time: '03:26',
    des: "一首空灵清澈令人感动令人着迷的天籁吟唱 \n 唯美的旋律，迷人的天籁，如空谷的风轻柔不羁，空灵清澈地吟唱着美丽与哀愁，让人怀想起那些曾经青涩而纯真的画面。 \n西丝尔(Sissel Kyrkjebo)挪威著名的女歌手，正如电影《泰坦尼克》配乐中那幽幽天籁，其歌声总能抚慰感伤的心绪。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "斯卡布罗集市 (Scarborough Fair) - 卡洛儿",
    song_file: "斯卡布罗集市.mp3",
    img_file: "卡洛儿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "卡洛儿",
    time: '04:24',
    des: "完美的女声吟唱。选自卡洛儿《一尘不染》",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "斯卡布罗集市 - Sarah Brightman",
    song_file: "斯卡布罗集市 - Sarah Brightman.mp3",
    img_file: "Simon & Garfunkel.jpeg",
    lyrics_file: '斯卡布罗集市.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "莎拉·布莱曼",
    time: '04:16',
    des: "《斯卡布罗集市》仿佛在倾诉什么，细雨敲窗的秋夜，她的倾诉，能把你带进逝去的情感伤痛中，回味曾经拥有的凄美的爱恋；\n心情烦躁的时候，她的倾诉，能把你带进寂静山林的深处，静坐在纯洁净美的幽谷里冷却自我；\n春风得意的时候，她的倾诉，能把你带进空灵梦幻苍穹里，感受并憧憬充满希望未来人生。\n总之，无论何时何地，《斯卡布罗集市》的天籁之声能陪你的心灵一起悲欢、一同祈祷……",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "我的歌声里-钢琴曲",
    song_file: "我的歌声里-钢琴曲.mp3",
    img_file: "我的歌声里.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "赵海洋",
    time: '03:29',
    des: "你没有办法在这个忘却的世间用声音来将谁记得\n回忆过了期\n你已不再年少\n病态\n焦躁\n彷徨还有不安\n尽管是这样不堪的我\n仍想牵着你的手\n拼尽整个青春\n与你一同到天涯\n她在我的梦里。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "残月（排箫）芈月传 - 王备",
    song_file: "西风（排箫）.mp3",
    img_file: "西风.png",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "王备",
    time: '05:04',
    des: "一曲琴韵瑟瑟，悲欢尘世离合。\n醮一抹沧桑，盈满袖暗香，将尘俗情思泯于无痕。\n在指间舞落一世繁华，弹尽一曲浪漫忧伤。\n掮一轮皓月，携一缕清风，穿越千年尘烟。\n寂寞纤指滑过灵魂的忧伤，多少深情未了。\n多少笑泪飞扬，蓦然回首，惘然一梦，\n惘然回顾中，却早已遗失了你。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "一叶子 - 林键标",
    song_file: "一叶子 - 林键标.mp3",
    img_file: "一叶子.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "林键标",
    time: '03:16',
    des: "独孤轻吟",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "秋日私语 - Richard Clayderman",
    song_file: "秋日私语 - Richard Clayderman.mp3",
    img_file: "15.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Richard Clayderman",
    time: '03:22',
    des: "那日的午后",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "醉清风 - 弦子",
    song_file: "醉清风 - 弦子.mp3",
    img_file: "16.jpg",
    lyrics_file: '醉清风.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "弦子",
    time: '05:07',
    des: "且听清风拂过。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "寂静的天空 (来自草原的寂静天籁) - 代青塔娜",
    song_file: "寂静的天空 (来自草原的寂静天籁) - 代青塔娜.mp3",
    img_file: " ",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "代青塔娜",
    time: '06:05',
    des: "在那风吹的草原\n有我心上的人\n风啊 你轻轻吹\n听他忧伤的歌\n月亮啊 你照亮他\n火光啊 你温暖他\n在那遥远的天空 有我思念的云\n夜莺呀 你轻声和\n听我静静地唱\n云啊 飘向何方\n心啊 随好流浪",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "送别 (口琴伴奏版) - 群星",
    song_file: "送别 (口琴伴奏版) - 群星.mp3",
    img_file: " ",
    lyrics_file: '送别.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "群星",
    time: '04:54',
    des: "愿漂泊的人有酒喝，愿孤独的人会唱歌。\n往前走，别回头。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "call of silence",
    song_file: "call of silence.MP3",
    img_file: " ",
    lyrics_file: 'call of silence.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "",
    time: '04:39',
    des: "成长不是变得坚强，是学会了什么都不说。",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "天空之城 - 久石让",
    song_file: "天空之城 - 久石让.mp3",
    img_file: "天空之城 - 久石让.webp",
    lyrics_file: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "久石让",
    time: '04:13',
    des: "",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "時代を越える想い - 和田薫",
    song_file: "時代を越える想い - 和田薫.mp3",
    img_file: "時代を越える想い - 和田薫.webp",
    lyrics_file: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "和田薫",
    time: '03:10',
    des: "",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "Illusionary Daytime(幻昼) - Shirfine",
    song_file: "Illusionary Daytime - Shirfine.mp3",
    img_file: "Illusionary Daytime - Shirfine.jpg",
    lyrics_file: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Shirfine",
    time: '04:10',
    des: "",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "You - Approaching Nirvana",
    song_file: "You - Approaching Nirvana.mp3",
    img_file: "You - Approaching Nirvana.jpg",
    lyrics_file: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Approaching Nirvana",
    time: '05:49',
    des: "",
  },
  {
    song_type: TYPE_2,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "Only Time - Enya",
    song_file: "Only Time - Enya.mp3",
    img_file: "Only Time - Enya.jpg",
    lyrics_file: "Only Time - Enya.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Enya",
    time: '03:38',
    des: "",
  },

]


//emo  不经意间 你已经悄然离去 只留下一段回忆  很遗憾，我没能成为你的偏爱和例外
const musicList3 = [
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "堕",
    song_file: "堕 - 旺仔小乔.mp3",
    img_file: "堕.webp",
    lyrics_file: '堕 - 旺仔小乔.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Zyboy忠宇",
    time: '03:06',
    des: "爱不是突然坠落的，是从一点点心软开始的。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "무지개는 있다 (Band Ver.) - Vincent Blue 有彩虹",
    song_file: "有彩虹.mp3",
    img_file: "有彩虹.webp",
    lyrics_file: '有彩虹.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "빈센트 블루 (Vincent Blue)",
    time: '03:23',
    des: "谢谢你， 听尽了我不堪的人生， 仍选择站在我这边。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "ありがとう（泪的告白）",
    song_file: "泪的告白.mp3",
    img_file: "泪的告白.jpg",
    lyrics_file: '泪的告白.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "墓辰倾心",
    time: '04:11',
    des: "遇见的都是幸运，或许下次见面真的只能靠运气了。然而我几乎不出门啊",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "十一种孤独",
    song_file: "十一种孤独 - 宿羽阳.mp3",
    img_file: "十一种孤独.webp",
    lyrics_file: '十一种孤独.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宿羽阳",
    time: '04:41',
    des: "如果一个人住，千万不要在下午睡午觉，一觉睡到六七点，等你一睁开眼，看着朦胧黑黑的天空和空荡的房间，会有一种被全世界遗弃的感觉，孤独在这一刻体现的淋漓尽致。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "十一年（翻自 邱永传） - 阿宇",
    song_file: "十一年（翻自 邱永传） - 阿宇.mp3",
    img_file: "十一年.webp",
    lyrics_file: '十一年.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "阿宇",
    time: '04:08',
    des: "2011年，那年大一，这个调调成了永远的痛。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "净化心灵的声音 (Moon Temple) - Karunesh",
    song_file: "(Moon Temple) - Karunesh.mp3",
    img_file: "Moon Temple.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Karunesh",
    time: '05:49',
    des: "Moon Temple中文意为\"庙堂\"，Zen Breakfast意为 道禅 。我想，专辑名为《道禅》是希望每一个听者都能从这飘缈的音乐声中，对社会，对人生，对情感有所感悟吧！\n在纷乱的现实生活中，在复杂的情感世界里，每一个人都活的很累。于是，人们都在尝试着找寻一个不被人所窥视的空间，卸下沉重的包袱，让不堪负重的心灵得到稍许的休憩。就在这一刻，就在《Moon Temple》响起的时候，人性、道德、情感恢复到了本原。尤其是在在钢琴和萧声中，似乎又多了一个空灵的女声，她用温柔和声轻柔的抚摸着每一个听者的心灵创伤。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "漠河舞厅·2022 - 柳爽",
    song_file: "漠河舞厅·2022 - 柳爽.mp3",
    img_file: "漠河舞厅·2022 - 柳爽.jpg",
    lyrics_file: '漠河舞厅.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "柳爽",
    time: '05:04',
    des: "\"人类用什么衡量爱?\"\n \"用分开后的痛苦.\"",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "丁香花 (2007版) - 唐磊",
    song_file: "丁香花 (2007版) - 唐磊.mp3",
    img_file: "丁香花 (2007版) - 唐磊.jpg",
    lyrics_file: '丁香花.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "唐磊",
    time: '04:25',
    des: "我再也没有见到过你，再也见不到了。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "청춘（青春） - 金必",
    song_file: "청춘 - 金必.mp3",
    img_file: "청춘 - 산울림（青春）.jpg",
    lyrics_file: '청춘 - 金必.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Sanullim",
    time: '03:39',
    des: "你是否想起了请回答1988呢",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "一生所爱 - 卢冠廷,莫文蔚",
    song_file: "一生所爱 - 卢冠廷,莫文蔚.mp3",
    img_file: "一生所爱 - 卢冠廷,莫文蔚.jpg",
    lyrics_file: '一生所爱.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "卢冠廷,莫文蔚",
    time: '04:33',
    des: "她的手只有我的手四分之三那么大，可我还是没能抓住。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "BINGBIAN病变 (女声版) - 鞠文娴",
    song_file: "BINGBIAN病变 (女声版) - 鞠文娴.mp3",
    img_file: "BINGBIAN病变 (女声版) - 鞠文娴.jpg",
    lyrics_file: 'BINGBIAN病变.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "鞠文娴",
    time: '04:07',
    des: "你要搞清楚，是你喜欢对方，不是人家喜欢你。\n既然你动心了，主动了，就算受了天大的委屈，也是预料中的事，怪不得任何人。你不是小朋友了，不开心不会死，结果只能自己承担，不管多难过，你也只能自己熬。\n谁叫你有本事喜欢人家，没本事让人家喜欢你呢。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "山海《完整版》cover(草东没有派对） - 万豹",
    song_file: "山海《完整版》cover(草东没有派对） - 万豹.mp3",
    img_file: "山海《完整版》cover(草东没有派对） - 万豹.jpg",
    lyrics_file: '山海.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "万豹",
    time: '04:09',
    des: "我们都太胆小了\n民国时不敢做军阀\n乱世里不敢去起义\n太平盛世不敢说我爱你",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "书房 - 顾君豪",
    song_file: "书房 - 顾君豪.mp3",
    img_file: "12.jpg",
    lyrics_file: '书房.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "顾君豪",
    time: '04:52',
    des: "这种感觉真的很糟\n因为一句话就高兴半天\n发现了一件事就心凉半截\n喜欢不能太明显 不然不值钱",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "清新的小女孩 (For Ma) - July Tun",
    song_file: "清新的小女孩 (For Ma) - July Tun.mp3",
    img_file: "14.jpg",
    lyrics_file: '清新的小女孩.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "July Tun",
    time: '04:01',
    des: "也许永远都不可能懂，但不影响她很好听。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "思君黯然 - 陈国樑",
    song_file: "思君黯然 - 陈国樑.mp3",
    img_file: "16.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "陈国樑",
    time: '01:36',
    des: "可我还是在等你，哪怕只是在心里。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "思君黯然 二胡版",
    song_file: "思君黯然 二胡版.mp3",
    img_file: "16.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "浩然ERHU",
    time: '01:26',
    des: "阿朱 。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "雪见—仙凡之旅 - 麦振鸿",
    song_file: "雪见—仙凡之旅 - 麦振鸿.mp3",
    img_file: "雪见—仙凡之旅 - 麦振鸿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "麦振鸿",
    time: '04:50',
    des: "记得那个为爱掏心的红毛怪，有着无尽相思的夕瑶，等待千年的龙葵，为老大割肉的茂茂，假装背叛死无全尸的必平，纠缠了三生三世放不下的紫萱和徐长卿，还有那个用自己的命换天下人复活的景天，以思念幻化成型的雪见。都说景天负了夕瑶，只有夕瑶知道，景天不是飞蓬。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "共伴闯天涯 - 麦振鸿",
    song_file: "共伴闯天涯 - 麦振鸿.mp3",
    img_file: "共伴闯天涯 - 麦振鸿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "麦振鸿",
    time: '03:22',
    des: "你最心疼编剧给哪个角色写死了  \"——茂茂，我们到长安了！\"",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "The Sound Of Silence - Simon & Garfunkel",
    song_file: "The Sound Of Silence - Simon & Garfunkel.mp3",
    img_file: "The Sound Of Silence - Simon & Garfunkel.jpg",
    lyrics_file: 'The Sound Of Silence.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Simon & Garfunkel",
    time: '03:05',
    des: "当我独自走在路上，在街道的灯光笼罩下，我看见人头攒动，有的人在说着无聊的话，有的人在听着别人说着无聊的话。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "无期-石白其",
    song_file: "无期-石白其.mp3",
    img_file: "无期.webp",
    lyrics_file: '无期.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "石白其",
    time: '02:41',
    des: "我喜欢你",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "有没有人告诉你 - 陈楚生",
    song_file: "有没有人告诉你 - 陈楚生.mp3",
    img_file: "有没有人告诉你 - 陈楚生.jpg",
    lyrics_file: '有没有人告诉你.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈楚生",
    time: '04:21',
    des: "我们之间再无交集。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "假如爱有天意 (Live) - 李健",
    song_file: "假如爱有天意 (Live) - 李健.mp3",
    img_file: " ",
    lyrics_file: '假如爱有天意.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李健",
    time: '05:13',
    des: "我们真的愿意为一个人变成更好的自己。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "灰色空间 - 罗志祥",
    song_file: "灰色空间 - 罗志祥.mp3",
    img_file: " ",
    lyrics_file: '灰色空间.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李健",
    time: '03:57',
    des: "灰色空间我是谁",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "Daughter of heaven - 段玫梅",
    song_file: "Daughter of heaven - 段玫梅.mp3",
    img_file: " ",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "段玫梅",
    time: '04:18',
    des: "她不是被命运选中的人，她是把命运握在手里的那个人。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "后来-刘若英",
    song_file: "后来-刘若英.MP3",
    img_file: " ",
    lyrics_file: '后来.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宋冬野",
    time: '05:41',
    des: "我曾经以为你会一直在，后来才知道，有的人走了就是走了。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "我用什么把你留住-福禄寿",
    song_file: "我用什么把你留住-福禄寿.MP3",
    img_file: " ",
    lyrics_file: '我用什么把你留住.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "福禄寿",
    time: '05:29',
    des: "我问过自己很多次：如果我再努力一点，你会不会留下？可惜答案永远都是沉默。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "那些年 - 胡夏",
    song_file: "那些年 - 胡夏.mp3",
    img_file: " ",
    lyrics_file: '那些年 - 胡夏.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "胡夏",
    time: '06:11',
    des: "青春最心酸的地方，就是回头看，每个瞬间都以为会永远。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "黄昏 - 周传雄",
    song_file: "黄昏 - 周传雄.mp3",
    img_file: " ",
    lyrics_file: '黄昏 - 周传雄.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "周传雄",
    time: '05:44',
    des: "我以为我不会再想你了，但是当我听到这首歌时，我才发现我错了。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "求佛 - 誓言",
    song_file: "求佛 - 誓言.mp3",
    img_file: " ",
    lyrics_file: '求佛 - 誓言.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "誓言",
    time: '04:46',
    des: "求佛，求佛，求佛。",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "卜卦 - 崔子格",
    song_file: "卜卦 - 崔子格.mp3",
    img_file: "卜卦 - 崔子格.webp",
    lyrics_file: '卜卦 - 崔子格.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "崔子格",
    time: '03:36',
    des: "卜卦",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "犯错 - 顾峰",
    song_file: "犯错 - 顾峰.mp3",
    img_file: "犯错 - 顾峰.jpg",
    lyrics_file: '犯错 - 顾峰.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "顾峰",
    time: '03:16',
    des: "犯错",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "阿拉斯加海湾 - 蓝心羽",
    song_file: "阿拉斯加海湾 - 蓝心羽.mp3",
    img_file: "阿拉斯加海湾 - 蓝心羽.jpg",
    lyrics_file: '阿拉斯加海湾 - 蓝心羽.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "蓝心羽",
    time: '04:01',
    des: "阿拉斯加海湾",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "凄美地 - 郭顶",
    song_file: "凄美地 - 郭顶.mp3",
    img_file: "凄美地 - 郭顶.jpg",
    lyrics_file: '凄美地 - 郭顶.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "郭顶",
    time: '04:10',
    des: "凄美地",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "悬溺 - 旺仔小乔",
    song_file: "悬溺 - 旺仔小乔.mp3",
    img_file: "悬溺 - 旺仔小乔.webp",
    lyrics_file: '悬溺 - 旺仔小乔.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "旺仔小乔",
    time: '03:17',
    des: "悬溺",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "烟火里的尘埃 - 华晨宇",
    song_file: "烟火里的尘埃 - 华晨宇.mp3",
    img_file: "烟火里的尘埃 - 华晨宇.jpg",
    lyrics_file: '烟火里的尘埃 - 华晨宇.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "华晨宇",
    time: '05:21',
    des: "烟火里的尘埃",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "海底 - 一支榴莲",
    song_file: "海底 - 一支榴莲.mp3",
    img_file: "海底 - 一支榴莲.jpg",
    lyrics_file: '海底 - 一支榴莲.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "一支榴莲",
    time: '04:16',
    des: "海底",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "好想爱这个世界啊 - 华晨宇",
    song_file: "好想爱这个世界啊 - 华晨宇.mp3",
    img_file: "好想爱这个世界啊 - 华晨宇.jpg",
    lyrics_file: '好想爱这个世界啊 - 华晨宇.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "华晨宇",
    time: '04:18',
    des: "好想爱这个世界啊",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "你从未离去 - 白挺",
    song_file: "你从未离去 - 白挺.mp3",
    img_file: "你从未离去 - 白挺.webp",
    lyrics_file: '你从未离去 - 白挺.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "白挺",
    time: '03:23',
    des: "你从未离去",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "三生石下 - 大欢",
    song_file: "三生石下 - 大欢.mp3",
    img_file: "三生石下 - 大欢.webp",
    lyrics_file: '三生石下 - 大欢.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "大欢",
    time: '04:23',
    des: "三生石下",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "拯救 - 孙楠",
    song_file: "拯救 - 孙楠.mp3",
    img_file: "拯救 - 孙楠.webp",
    lyrics_file: '拯救 - 孙楠.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "孙楠",
    time: '05:32',
    des: "拯救",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "真爱的力量 - Maj7_Music 巴音孟克",
    song_file: "真爱的力量 - Maj7_Music 巴音孟克.mp3",
    img_file: "真爱的力量 - Maj7_Music 巴音孟克.webp",
    lyrics_file: '真爱的力量 - Maj7_Music 巴音孟克.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Maj7_Music 巴音孟克",
    time: '03:59',
    des: "真爱的力量",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "凉凉 - 杨宗纬",
    song_file: "凉凉 - 杨宗纬.mp3",
    img_file: "凉凉 - 杨宗纬.webp",
    lyrics_file: '凉凉 - 杨宗纬.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "杨宗纬",
    time: '05:33',
    des: "凉凉",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "不要再来伤害我 - 张振宇",
    song_file: "不要再来伤害我 - 张振宇.mp3",
    img_file: "不要再来伤害我 - 张振宇.jpg",
    lyrics_file: '不要再来伤害我 - 张振宇.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张振宇",
    time: '05:23',
    des: "不要再来伤害我",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "再次见到你 _Once Again（翻自 Mad Clown&金娜英） - 阿YueYue",
    song_file: "再次见到你 _Once Again（翻自 Mad Clown&金娜英） - 阿YueYue.mp3",
    img_file: "再次见到你 _Once Again（翻自 Mad Clown&金娜英） - 阿YueYue.jpg",
    lyrics_file: '再次见到你 _Once Again（翻自 Mad Clown&金娜英） - 阿YueYue.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "阿YueYue",
    time: '03:16',
    des: "再次见到你",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "你走 - 李宗锦（松紧先生）",
    song_file: "你走 - 李宗锦（松紧先生）.mp3",
    img_file: "你走 - 李宗锦（松紧先生）.jpg",
    lyrics_file: '你走 - 李宗锦（松紧先生）.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李宗锦（松紧先生）",
    time: '04:04',
    des: "你走",
  },
  {
    song_type: TYPE_3,
    song_path: FILE_MUSIC_EMO,
    song_name: "她 - 不可撤销乐队",
    song_file: "她 - 不可撤销乐队.mp3",
    img_file: "她 - 不可撤销乐队.jpg",
    lyrics_file: '她 - 不可撤销乐队.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "不可撤销乐队",
    time: '04:32',
    des: "她",
  },
]

//经典
const musicList4 = [
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "夜空中最亮的星 - 逃跑计划",
    song_file: "夜空中最亮的星 - 逃跑计划.mp3",
    img_file: "  ",
    lyrics_file: '夜空中最亮的星 - 逃跑计划.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "逃跑计划",
    time: '04:12',
    des: "黑暗多的时候，我就抬头找光。不是为了看得更远，而是为了让自己不倒下。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "我的歌声里-曲婉婷",
    song_file: "我的歌声里-曲婉婷.mp3",
    img_file: "  ",
    lyrics_file: '我的歌声里 - 曲婉婷.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "曲婉婷",
    time: '03:37',
    des: "最心酸的不是忘不掉，而是突然在街角听到这首歌时，一秒就想起你。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "我好想你-苏打绿",
    song_file: "我好想你-苏打绿.mp3",
    img_file: "  ",
    lyrics_file: '我好想你.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "苏打绿",
    time: '05:24',
    des: "这首歌每一句都像在替我说：我很好，也很想你，只是你不知道。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "水木年华 - 一生有你",
    song_file: "水木年华 - 一生有你.mp3",
    img_file: "  ",
    lyrics_file: '一生有你.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "水木年华",
    time: '04:18',
    des: "此生未曾拥有。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "陈一发儿 - 童话镇",
    song_file: "陈一发儿 - 童话镇.mp3",
    img_file: "  ",
    lyrics_file: '童话镇.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈一发儿",
    time: '04:18',
    des: "沉浸在童话的世界里不愿醒来。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "大海 - 张雨生",
    song_file: "大海 - 张雨生.mp3",
    img_file: "  ",
    lyrics_file: '大海.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张雨生",
    time: '04:40',
    des: "你是我这辈子跨不过去的大海，无论我在岸上喊得多用力，你都不会再回应了。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "星星点灯 - 郑智化",
    song_file: "星星点灯 - 郑智化.mp3",
    img_file: "  ",
    lyrics_file: '星星点灯.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "郑智化",
    time: '05:00',
    des: "黑暗并不可怕，可怕的是忘了抬头看看那盏属于自己的灯。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "老鼠爱大米 - 杨臣刚",
    song_file: "老鼠爱大米 - 杨臣刚.mp3",
    img_file: "  ",
    lyrics_file: '老鼠爱大米 - 香香.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "杨臣刚",
    time: '05:04',
    des: "今天语文老师教我们文言文中\"之\"的取独用法，以本歌经典歌词为例，翻译成了古汉语：\"吾之爱汝，如鼠之爱粟。\"简直印象不能再深刻[大哭][大哭][大哭]",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "老鼠爱大米 - 香香",
    song_file: "老鼠爱大米 - 香香.mp3",
    img_file: "  ",
    lyrics_file: '老鼠爱大米 - 香香.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "香香",
    time: '05:01',
    des: "今天语文老师教我们文言文中\"之\"的取独用法，以本歌经典歌词为例，翻译成了古汉语：\"吾之爱汝，如鼠之爱粟。\"简直印象不能再深刻[大哭][大哭][大哭]",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "奇妙能力歌 - 陈粒",
    song_file: "奇妙能力歌 - 陈粒.mp3",
    img_file: "  ",
    lyrics_file: '奇妙能力歌.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈粒",
    time: '04:13',
    des: "我听过一万首歌，看过一千部电影，读过一百本书，却从未俘获一个人的心。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "此生不换",
    song_file: "此生不换 - 青鸟飞鱼.mp3",
    img_file: "此生不换.jpg",
    lyrics_file: '此生不换.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "青鸟飞鱼",
    time: '04:25',
    des: "在初中暗恋三年的同桌，有一天看见她在折星星，\n我问她，这是送给谁的啊，她说，送给她最爱的人，\n过了几天，她送了个熊娃娃给我，我在想，那些星星她是送给谁的?\n过了很多年，我结婚了，生了孩子，把熊给孩子玩，\n一天，孩子不小心把熊撕破了，一大把的星星掉了出来，我顿时泪目。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "断点",
    song_file: "断点.mp3",
    img_file: "断点.jpg",
    lyrics_file: '断点.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张敬轩",
    time: '04:28',
    des: "其实我挺羡慕火车的。 \n  为什么? \n 他们连擦肩而过都那么久。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "美人吟 - 李玲玉",
    song_file: "美人吟 - 李玲玉.mp3",
    img_file: "美人吟 - 李玲玉.jpg",
    lyrics_file: '美人吟.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李玲玉",
    time: '04:02',
    des: "舒畅。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "天顶一粒星 - Tizzy T,宋佳",
    song_file: "天顶一粒星 - Tizzy T,宋佳.mp3",
    img_file: "9.jpg",
    lyrics_file: '天顶一粒星.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Tizzy T,宋佳",
    time: '03:53',
    des: "嘿呀嘿呀咿儿呀",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "仙剑问情(主题曲) - 萧人凤",
    song_file: "仙剑问情(主题曲) - 萧人凤.mp3",
    img_file: "仙剑问情(主题曲) - 萧人凤.jpg",
    lyrics_file: '仙剑问情.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "萧人凤",
    time: '04:16',
    des: "我李逍遥可以对天发誓从今以后不会再让你一人孤苦伶仃。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "雨花石（电视连续剧《红红的雨花石》主题歌）",
    song_file: "雨花石（电视连续剧《红红的雨花石》主题歌）.mp3",
    img_file: " ",
    lyrics_file: '雨花石.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈每文、熊健萍、陈帆等",
    time: '03:49',
    des: "我是一颗小小的石头",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "偏爱-张芸京",
    song_file: "偏爱-张芸京.MP3",
    img_file: " ",
    lyrics_file: '偏爱.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张芸京",
    time: '03:33',
    des: "如此喜欢你的偏爱",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "唯一-告五人",
    song_file: "唯一-告五人.MP3",
    img_file: " ",
    lyrics_file: '唯一.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "告五人",
    time: '04:31',
    des: "我一直很清楚，喜欢你这件事，从来没办法平均分给别人。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "不浪漫罪名-王杰",
    song_file: "不浪漫罪名-王杰.MP3",
    img_file: " ",
    lyrics_file: '不浪漫罪名.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "王杰",
    time: '04:43',
    des: "我犯下了滔天的罪名",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "下雨天-南拳妈妈",
    song_file: "下雨天-南拳妈妈.MP3",
    img_file: " ",
    lyrics_file: '下雨天.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "南拳妈妈",
    time: '04:13',
    des: "下雨天最适合想你，因为雨声刚好覆盖我所有没说出口的难过。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "一直很安静-阿桑",
    song_file: "一直很安静-阿桑.MP3",
    img_file: " ",
    lyrics_file: '一直很安静.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "阿桑",
    time: '04:07',
    des: "有些心碎从来都没有声音，所以没人知道你有多难过。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "明天，你好 - 牛奶咖啡",
    song_file: "明天，你好 - 牛奶咖啡.mp3",
    img_file: " ",
    lyrics_file: '明天，你好 - 牛奶咖啡.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "牛奶咖啡",
    time: '04:31',
    des: "今天的你也许很累，但请相信——明天的风，会比今天温柔一点。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "越长大越孤单 - 牛奶咖啡",
    song_file: "越长大越孤单 - 牛奶咖啡.mp3",
    img_file: " ",
    lyrics_file: '越长大越孤单 - 牛奶咖啡.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "牛奶咖啡",
    time: '04:28',
    des: "小时候害怕黑暗，长大后害怕沉默。越长大，越发现能说真话的人越来越少。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "那些花儿 - 朴树",
    song_file: "那些花儿 - 朴树.mp3",
    img_file: " ",
    lyrics_file: '那些花儿 - 朴树.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "朴树",
    time: '04:55',
    des: "那些走丢的人，那些开过的花，都住在我心里最柔软的地方。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "生生世世爱 - 吴雨霏 ",
    song_file: "生生世世爱 - 吴雨霏.mp3",
    img_file: " ",
    lyrics_file: '生生世世爱 - 吴雨霏.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "吴雨霏",
    time: '04:41',
    des: "我以为生生世世很长，可以慢慢等你。后来才懂，来日并不方长，喜欢的人也会走散。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "空白格 - 杨宗纬",
    song_file: "空白格 - 杨宗纬.mp3",
    img_file: " ",
    lyrics_file: '空白格 - 杨宗纬.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "杨宗纬",
    time: '03:38',
    des: "我以为我会是最坚强的那一个，我还是高估了自己。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "绿光 - 孙燕姿",
    song_file: "绿光 - 孙燕姿.mp3",
    img_file: " ",
    lyrics_file: '绿光 - 孙燕姿.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "孙燕姿",
    time: '03:11',
    des: "我想超越这平凡的生活，注定现在暂时漂泊。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "我怀念的 - 孙燕姿",
    song_file: "我怀念的 - 孙燕姿.mp3",
    img_file: " ",
    lyrics_file: '我怀念的 - 孙燕姿.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "孙燕姿",
    time: '04:50',
    des: "我怀念的，是什么？",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "七里香 - 周杰伦",
    song_file: "七里香 - 周杰伦.mp3",
    img_file: " ",
    lyrics_file: '七里香 - 周杰伦.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "周杰伦",
    time: '04:59',
    des: "窗外的麻雀在电线杆上多嘴，你说这一句很有夏天的感觉。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "寂寞沙洲冷 - 周传雄",
    song_file: "寂寞沙洲冷 - 周传雄.mp3",
    img_file: " ",
    lyrics_file: '寂寞沙洲冷 - 周传雄.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "周传雄",
    time: '04:37',
    des: "当记忆的线",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "My Heart Will Go On (Love Theme from _Titanic_) - Céline Dion",
    song_file: "My Heart Will Go On (Love Theme from _Titanic_) - Céline Dion.mp3",
    img_file: " ",
    lyrics_file: 'My Heart Will Go On (Love Theme from _Titanic_) - Céline Dion.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Céline Dion",
    time: '05:10',
    des: "我心永恒",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "传奇 - 李健",
    song_file: "传奇 - 李健.mp3",
    img_file: " ",
    lyrics_file: '传奇 - 李健.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李健",
    time: '05:24',
    des: "只是因为在人群中多看了你一眼，再也没能忘掉你容颜。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "倩女幽魂 - 张国荣",
    song_file: "倩女幽魂 - 张国荣.mp3",
    img_file: " ",
    lyrics_file: '倩女幽魂 - 张国荣.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张国荣",
    time: '03:37',
    des: "倩女幽魂，倩女幽魂。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "怎么说我不爱你 - 萧敬腾",
    song_file: "怎么说我不爱你 - 萧敬腾.mp3",
    img_file: " ",
    lyrics_file: '怎么说我不爱你 - 萧敬腾.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "萧敬腾",
    time: '04:35',
    des: "怎么说我不爱你",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "九儿 - 胡莎莎",
    song_file: "九儿 - 胡莎莎.mp3",
    img_file: "九儿.jpg",
    lyrics_file: '九儿 - 胡莎莎.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "胡莎莎",
    time: '02:28',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "Lonely - Nana",
    song_file: "Lonely - Nana.mp3",
    img_file: "Lonely - Nana.jpg",
    lyrics_file: 'Lonely - Nana.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Nana",
    time: '06:21',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "旅行 - 许巍",
    song_file: "旅行 - 许巍.mp3",
    img_file: "旅行 - 许巍.jpg",
    lyrics_file: '旅行 - 许巍.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "许巍",
    time: '04:26',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "北郊 - 迟志强",
    song_file: "北郊 - 迟志强.mp3",
    img_file: "",
    lyrics_file: '北郊 - 迟志强.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: '05:05',
    des: "如果当时",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "铁窗泪 - 迟志强",
    song_file: "铁窗泪 - 迟志强.mp3",
    img_file: "铁窗泪 - 迟志强.webp",
    lyrics_file: '铁窗泪 - 迟志强.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: '08:27',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "钞票 - 迟志强",
    song_file: "钞票 - 迟志强.mp3",
    img_file: "",
    lyrics_file: '钞票 - 迟志强.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: '03:09',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "愁啊愁 - 迟志强",
    song_file: "愁啊愁 - 迟志强.mp3",
    img_file: "",
    lyrics_file: '愁啊愁 - 迟志强.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: '04:43',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "狱中十二月 - 迟志强",
    song_file: "狱中十二月 - 迟志强.mp3",
    img_file: "狱中十二月 - 迟志强.webp",
    lyrics_file: '狱中十二月 - 迟志强.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: '03:07',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "打工十二月 - 翟惠民",
    song_file: "打工十二月 - 翟惠民.mp3",
    img_file: "打工十二月 - 翟惠民.jpg",
    lyrics_file: '打工十二月 - 翟惠民.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "翟惠民",
    time: '06:08',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "流浪歌 - 迟志强",
    song_file: "流浪歌 - 迟志强.mp3",
    img_file: "流浪歌 - 迟志强.webp",
    lyrics_file: '流浪歌 - 迟志强.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: '04:57',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "记事本 - 陈慧琳",
    song_file: "记事本 - 陈慧琳.mp3",
    img_file: "记事本 - 陈慧琳.jpg",
    lyrics_file: '记事本 - 陈慧琳.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈慧琳",
    time: '04:11',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "丫头 - 王童语",
    song_file: "丫头 - 王童语.mp3",
    img_file: "丫头 - 王童语.webp",
    lyrics_file: '丫头 - 王童语.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "王童语",
    time: '05:32',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "真的爱你 - BEYOND",
    song_file: "真的爱你 - BEYOND.mp3",
    img_file: "真的爱你 - BEYOND.webp",
    lyrics_file: '真的爱你 - BEYOND.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: '04:35',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "情人 - BEYOND",
    song_file: "情人_Beyond.mp3",
    img_file: "情人_Beyond.jpg",
    lyrics_file: '情人_Beyond.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: '05:18',
    des: "情人，情人，情人。",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "光辉岁月 - BEYOND",
    song_file: "光辉岁月 - BEYOND.mp3",
    img_file: "光辉岁月 - BEYOND.webp",
    lyrics_file: '光辉岁月 - BEYOND.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: '05:02',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "喜欢你 - BEYOND",
    song_file: "喜欢你 - BEYOND.mp3",
    img_file: "喜欢你 - BEYOND.webp",
    lyrics_file: '喜欢你 - BEYOND.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: '04:34',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "海阔天空 - BEYOND",
    song_file: "海阔天空 - BEYOND.mp3",
    img_file: "海阔天空 - BEYOND.webp",
    lyrics_file: '海阔天空 - BEYOND.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: '05:25',
    des: "",
  },
  {
    song_type: TYPE_4,
    song_path: FILE_MUSIC_JINGDIAN,
    song_name: "灰色轨迹 - BEYOND",
    song_file: "灰色轨迹 - Beyond.mp3",
    img_file: "灰色轨迹 - Beyond.jpg",
    lyrics_file: '灰色轨迹 - Beyond.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: '05:25',
    des: "",
  },
]

//气势 BGM
const musicList5 = [
  {
    song_type: TYPE_5,
    song_path: FILE_MUSIC_BGM,
    song_name: "亡灵序曲 (The Dawn) - Dreamtale",
    song_file: "The Dawn_亡灵序曲.mp3",
    img_file: "亡灵序曲.jpg",
    lyrics_file: '大地 - BEYOND.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Dreamtale",
    time: '04:06',
    des: "《The Dawn》的原意为黎明、拂晓、破晓，但在国内网络上，广被讹传为\"亡灵序曲\"。",
  },
  {
    song_type: TYPE_5,
    song_path: FILE_MUSIC_BGM,
    song_name: "伊卡洛斯 Icarus - Ivan Torrent",
    song_file: "icarus.mp3",
    img_file: "Ivan Torrent.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Ivan Torrent",
    time: '04:35',
    des: "Ivan Torrent 是西班牙一个独立作曲家和制作人。为流行音乐和舞蹈艺术家在西班牙工作多年，作为一个设计师，也为广播电台做广告宣传和广告歌曲。现在Ivan Torrent想更专注于电影音乐的场景，为预告片音乐公司工作，以及做演示样品库。",
  },
]

//律动
const musicList6 = [
  {
    song_type: TYPE_6,
    song_path: FILE_MUSIC_lvdong,
    song_name: "Fade - Alan Walker",
    song_file: "Fade - Alan Walker.mp3",
    img_file: "Fade - Alan Walker.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Alan Walker",
    time: '04:24',
    des: "跑起来吧",
  },
  {
    song_type: TYPE_6,
    song_path: FILE_MUSIC_lvdong,
    song_name: "Something Just Like This - The Chainsmokers,Coldplay",
    song_file: "Something Just Like This - The Chainsmokers,Coldplay.mp3",
    img_file: "Something Just Like This - The Chainsmokers,Coldplay.jpg",
    lyrics_file: 'Something Just Like This.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "The Chainsmokers,Coldplay",
    time: '04:07',
    des: "喜欢iPad你就去买，喜欢莱卡你就去赚，想喝港式奶茶你就过口岸，想当team leader你就努力学习然后努力去工作，想去威尼斯你就攒钱去，想爱谁你就去爱，想追谁你就去追，想到了就去做，拼命努力，拼命享受，忍着守着惦记着，青春就过去了，何必用40岁的心态过20岁的年华。",
  },
  {
    song_type: TYPE_6,
    song_path: FILE_MUSIC_lvdong,
    song_name: "Dream It Possible - Delacey",
    song_file: "Dream It Possible - Delacey.mp3",
    img_file: "1.jpg",
    lyrics_file: 'Dream It Possible.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Delacey",
    time: '03:24',
    des: "不用等梦想成真，只要每天做一点点。",
  },
  {
    song_type: TYPE_6,
    song_path: FILE_MUSIC_lvdong,
    song_name: "挪威的森林 - 伍佰",
    song_file: "挪威的森林 - 伍佰.mp3",
    img_file: "挪威的森林 - 伍佰.jpg",
    lyrics_file: '挪威的森林.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "伍佰",
    time: '06:33',
    des: "心中是否有我未曾到过的地方啊",
  },
  {
    song_type: TYPE_6,
    song_path: FILE_MUSIC_lvdong,
    song_name: "dance monkey - Tones and I",
    song_file: "dance monkey - Tones and I.mp3",
    img_file: " ",
    lyrics_file: 'dance monkey - Tones and I.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Tones and I",
    time: '03:30',
    des: "I'm a dance monkey, I'm a dance monkey, I'm a dance monkey.",
  },
  {
    song_type: TYPE_6,
    song_path: FILE_MUSIC_lvdong,
    song_name: "街角的晚风 (粤语小春版) - 善宇",
    song_file: "街角的晚风 (粤语小春版) - 善宇.mp3",
    img_file: " ",
    lyrics_file: '街角的晚风 (粤语小春版) - 善宇.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "善宇",
    time: '02:35',
    des: "",
  },
  {
    song_type: TYPE_6,
    song_path: FILE_MUSIC_lvdong,
    song_name: "追梦赤子心 - GALA",
    song_file: "追梦赤子心 - GALA.mp3",
    img_file: "追梦赤子心 - GALA.jpg",
    lyrics_file: '追梦赤子心 - GALA.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "GALA",
    time: '05:18',
    des: "",
  },
]


//动画片
const musicList7 = [
  {
    song_type: TYPE_7,
    song_path: FILE_MUSIC_donghuapian,
    song_name: "灌篮高手 - 好想大声说爱你",
    song_file: "灌篮高手 - 好想大声说爱你.mp3",
    img_file: "灌篮高手 - 好想大声说爱你.jpg",
    lyrics_file: '灌篮高手 - 好想大声说爱你.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "",
    time: '03:51',
    des: "",
  },
  {
    song_type: TYPE_7,
    song_path: FILE_MUSIC_donghuapian,
    song_name: "数码宝贝 - ButterFly - 和田光司",
    song_file: "数码宝贝 - Butter-Fly - 和田光司.mp3",
    img_file: "数码宝贝 - Butter-Fly - 和田光司.webp",
    lyrics_file: '数码宝贝 - Butter-Fly - 和田光司.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "和田光司",
    time: '04:18',
    des: "",
  },
  {
    song_type: TYPE_7,
    song_path: FILE_MUSIC_donghuapian,
    song_name: "数码宝贝 - brave heart - 宮崎歩",
    song_file: "数码宝贝 - brave heart - 宮崎歩.mp3",
    img_file: "数码宝贝 - brave heart - 宮崎歩.jpg",
    lyrics_file: '数码宝贝 - brave heart - 宮崎歩.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: " 宮崎歩",
    time: '04:12',
    des: "",
  },
  {
    song_type: TYPE_7,
    song_path: FILE_MUSIC_donghuapian,
    song_name: "龙珠 - 魔訶不思議アドベンチャー - 高橋洋樹",
    song_file: "龙珠.mp3",
    img_file: "龙珠.jpg",
    lyrics_file: '龙珠.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "高橋洋樹",
    time: '03:50',
    des: "",
  },
  {
    song_type: TYPE_7,
    song_path: FILE_MUSIC_donghuapian,
    song_name: "光能使者 - 光、出でよ、汝グランゾート - 田中公平",
    song_file: "光能使者 - 光、出でよ、汝グランゾート - 田中公平.mp3",
    img_file: "光能使者 - 光、出でよ、汝グランゾート - 田中公平.webp",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "田中公平",
    time: '02:52',
    des: "",
  },
  {
    song_type: TYPE_7,
    song_path: FILE_MUSIC_donghuapian,
    song_name: "憨八龟的故事 - 生命的云彩",
    song_file: "生命的云彩 - 沸点乐队.mp3",
    img_file: "",
    lyrics_file: '生命的云彩 - 沸点乐队.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "沸点乐队",
    time: '02:16',
    des: "",
  },



]

//民谣
const musicList8 = [
{
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "安和桥 - 宋冬野",
    song_file: "安和桥 - 宋冬野.mp3",
    img_file: "",
    lyrics_file: '安和桥 - 宋冬野.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宋冬野",
    time: '04:10',
    des: "村东头的狗都懂了遗憾的意义",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "斑马，斑马 - 宋冬野",
    song_file: "斑马，斑马 - 宋冬野.mp3",
    img_file: "",
    lyrics_file: '斑马，斑马 - 宋冬野.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宋冬野",
    time: '04:14',
    des: "世界如此广阔，人类却走进了悲伤的墙角。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "成都 - 赵雷",
    song_file: "成都 - 赵雷.mp3",
    img_file: "",
    lyrics_file: '成都 - 赵雷.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: '05:29',
    des: "我在这座城市听《成都》，它就变成了我的故事。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "春风十里 - 鹿先森乐队",
    song_file: "春风十里 - 鹿先森乐队.mp3",
    img_file: "",
    lyrics_file: '春风十里 - 鹿先森乐队.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "鹿先森乐队",
    time: '06:15',
    des: "不如遇见你。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "董小姐 - 宋冬野",
    song_file: "董小姐 - 宋冬野.mp3",
    img_file: "",
    lyrics_file: '董小姐 - 宋冬野.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宋冬野",
    time: '05:10',
    des: "求给陌生人一支兰州，我已经付了零钱和敬意。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "鼓楼 - 赵雷",
    song_file: "鼓楼 - 赵雷.mp3",
    img_file: "",
    lyrics_file: '鼓楼 - 赵雷.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: '04:41',
    des: "城市太大了，大到装得下所有烦恼，却装不下一个想拥抱的人。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "理想三旬 - 陈鸿宇",
    song_file: "理想三旬 - 陈鸿宇.mp3",
    img_file: "理想三旬 - 陈鸿宇.jpg",
    lyrics_file: '理想三旬 - 陈鸿宇.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈鸿宇",
    time: '03:30',
    des: "曾以为理想三旬，只是个诗意的词，后来才知道——是我们终究要长大的意思。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "南方姑娘 - 赵雷",
    song_file: "南方姑娘 - 赵雷.mp3",
    img_file: "",
    lyrics_file: '南方姑娘 - 赵雷.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: '05:32',
    des: "我会去南方么？我问我自己。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "白桦林 - 朴树",
    song_file: "白桦林 - 朴树.mp3",
    img_file: "",
    lyrics_file: '白桦林 - 朴树.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "朴树",
    time: '03:47',
    des: "最让人难受的不是他死在白桦林里，而是她永远不知道。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "我们的时光 - 赵雷",
    song_file: "我们的时光 - 赵雷.mp3",
    img_file: "我们的时光 - 赵雷.jpg",
    lyrics_file: '我们的时光 - 赵雷.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: '04:30',
    des: "我们的时光，我们的时光，我们的时光，我们的时光。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "南山南 - 马頔",
    song_file: "南山南 - 马頔.mp3",
    img_file: "南山南 - 马頔.jpg",
    lyrics_file: '南山南 - 马頔.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "马頔",
    time: '05:23',
    des: "南山南，北秋悲，南山有谷堆，南风喃，北海北，北海有墓碑。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "写给黄淮 - 邵帅",
    song_file: "写给黄淮 - 邵帅.mp3",
    img_file: "写给黄淮 - 邵帅.jpg",
    lyrics_file: '写给黄淮 - 邵帅.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "邵帅",
    time: '04:01',
    des: "写给黄淮，我们的时光，我们的时光，我们的时光。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "七月上 - Jam",
    song_file: "七月上 - Jam.mp3",
    img_file: "七月上 - Jam.jpg",
    lyrics_file: '七月上 - Jam.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Jam",
    time: '03:10',
    des: "我像个傻子一样记住了你。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "余香 - 张小九",
    song_file: "余香 - 张小九.mp3",
    img_file: "余香 - 张小九.jpg",
    lyrics_file: '余香 - 张小九.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张小九 ",
    time: '04:06',
    des: "余香，我们的时光，我们的时光，我们的时光。",
  },
  {
    song_type: TYPE_8,
    song_path: FILE_MUSIC_minyao,
    song_name: "云烟成雨 - 房东的猫",
    song_file: "云烟成雨 - 房东的猫.mp3",
    img_file: "云烟成雨 - 房东的猫.jpg",
    lyrics_file: '云烟成雨 - 房东的猫.lrc',
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "房东的猫",
    time: '04:00',
    des: "",
  },

]


// 统一管理所有音乐列表的存储
export const STORAGE_KEYS = {
  TIANLANZHIYIN: 'musicList1',
  QINGYINYUE: 'musicList2',
  EMO: 'musicList3',
  JINGDIAN: 'musicList4',
  BGM: 'musicList5',
  LVDONG: 'musicList6',
  DONGHUAPIAN: 'musicList7',
  MINYAO: 'musicList8'
};

const STORAGE_META_KEY = 'musicListStorageVersion';
const STORAGE_VERSION = '2026-02-25-v6';
const memoryStorage = new Map();

const safeStorage = {
  getItem(key) {
    try {
      return localStorage.getItem(key);
    } catch (_) {
      return memoryStorage.get(key) ?? null;
    }
  },
  setItem(key, value) {
    const normalizedValue = String(value);
    try {
      localStorage.setItem(key, normalizedValue);
    } catch (_) {
      memoryStorage.set(key, normalizedValue);
    }
  }
};

// 创建一个统一的存储管理类
export class MusicStorage {

  // 定义音乐类型枚举
  static MUSIC_TYPES = {
    TIANLANZHIYIN: { key: 'musicList1', label: '天籁之音' },
    QINGYINYUE: { key: 'musicList2', label: '轻音乐' },
    EMO: { key: 'musicList3', label: 'EMO' },
    JINGDIAN: { key: 'musicList4', label: '经典' },
    BGM: { key: 'musicList5', label: '气势BGM' },
    LVDONG: { key: 'musicList6', label: '律动' },
    DONGHUAPIAN: { key: 'musicList7', label: '动画片' },
    MINYAO: { key: 'musicList8', label: '民谣' }
  };
  // 定义音乐列表映射
  static musicListMap = {
    [STORAGE_KEYS.TIANLANZHIYIN]: musicList1,
    [STORAGE_KEYS.QINGYINYUE]: musicList2,
    [STORAGE_KEYS.EMO]: musicList3,
    [STORAGE_KEYS.JINGDIAN]: musicList4,
    [STORAGE_KEYS.BGM]: musicList5,
    [STORAGE_KEYS.LVDONG]: musicList6,
    [STORAGE_KEYS.DONGHUAPIAN]: musicList7,
    [STORAGE_KEYS.MINYAO]: musicList8
  };

  // 验证音乐对象
  static validateMusic(music) {
    return !!(
      music &&
      (music.song_name || music.title) &&
      (music.song_file || music.name_path) &&
      music.author !== undefined &&
      (music.song_type ?? music.type) !== undefined &&
      (music.song_path || music.type_path) !== undefined
    );
  }


  // 存储单个列表
  static saveList(key, list) {
    try {
      const validList = list.filter(this.validateMusic);
      safeStorage.setItem(key, JSON.stringify(validList));
      return true;
    } catch (error) {
      console.error(`存储音乐列表失败 (${key}):`, error);
      return false;
    }
  }

  // 获取单个列表
  static getList(key) {
    try {
      const list = JSON.parse(safeStorage.getItem(key)) || [];
      return list.filter(this.validateMusic);
    } catch (error) {
      console.error(`获取音乐列表失败 (${key}):`, error);
      return [];
    }
  }

  // 存储所有列表
  static saveAllLists() {
    return Object.entries(this.musicListMap)
      .map(([key, list]) => this.saveList(key, list))
      .every(Boolean);
  }


  // 获取所有音乐
  static getListAllMusic() {
    try {
      return Object.values(this.musicListMap)
        .flat()
        .filter(this.validateMusic);
    } catch (error) {
      console.error('获取所有音乐列表失败:', error);
      return [];
    }
  }
  // 按类型获取音乐
  static getListByType(type) {
    return this.musicListMap[type]?.filter(this.validateMusic) || [];
  }

  // 搜索音乐
  static searchMusic(keyword) {
    if (!keyword?.trim()) return [];

    const searchTerm = keyword.toLowerCase().trim();
    return this.getListAllMusic().filter(music =>
      (music.song_name || music.title || '').toLowerCase().includes(searchTerm) ||
      music.author.toLowerCase().includes(searchTerm) ||
      music.des?.toLowerCase().includes(searchTerm)
    );
  }

  // 获取随机音乐
  static getRandomMusic() {
    const allMusic = this.getListAllMusic();
    return allMusic[Math.floor(Math.random() * allMusic.length)];
  }

}

// 仅在首次加载或版本变更时更新本地缓存，避免每次启动全量写入
const shouldRefreshStorage = safeStorage.getItem(STORAGE_META_KEY) !== STORAGE_VERSION;
if (shouldRefreshStorage) {
  MusicStorage.saveAllLists();
  safeStorage.setItem(STORAGE_META_KEY, STORAGE_VERSION);
}

/**
 * 获取音乐列表
 */
export const getMusicList = (tabName) => {
  const tabMusicMap = {
    'tab-A': MusicStorage.getListAllMusic(),
    'tab-B': MusicStorage.getList(STORAGE_KEYS.TIANLANZHIYIN),
    'tab-C': MusicStorage.getList(STORAGE_KEYS.QINGYINYUE),
    'tab-D': MusicStorage.getList(STORAGE_KEYS.EMO),
    'tab-E': MusicStorage.getList(STORAGE_KEYS.JINGDIAN),
    'tab-F': MusicStorage.getList(STORAGE_KEYS.BGM),
    'tab-G': MusicStorage.getList(STORAGE_KEYS.LVDONG),
    'tab-H': MusicStorage.getList(STORAGE_KEYS.DONGHUAPIAN),
    'tab-I': MusicStorage.getList(STORAGE_KEYS.MINYAO)
  };
  return tabMusicMap[tabName] || [];
};
