import { CONFIG } from '../app/config.js';

const TYPE = "动漫影视";
const FILE_MUSIC_DONGMANYINGSHI = "dongmanyingshi/";

export const animeScreenList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "好想大声说爱你（君が好きだと叫びたい）",
    song_file: "灌篮高手 - 好想大声说爱你.mp3",
    img_file: "灌篮高手 - 好想大声说爱你.jpg",
    lyrics_file: "灌篮高手 - 好想大声说爱你.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BAAD",
    time: "03:51",
    des: "前奏一响，那个夏天的球场和没说出口的热血就都回来了。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "Butter-Fly",
    song_file: "数码宝贝 - Butter-Fly - 和田光司.mp3",
    img_file: "数码宝贝 - Butter-Fly - 和田光司.webp",
    lyrics_file: "数码宝贝 - Butter-Fly - 和田光司.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "和田光司",
    time: "04:18",
    des: "长大后才懂，这首歌唱的不是进化，是不肯认输的自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "brave heart《数码暴龙进化曲》",
    song_file: "数码宝贝 - brave heart - 宮崎歩.mp3",
    img_file: "数码宝贝 - brave heart - 宮崎歩.jpg",
    lyrics_file: "数码宝贝 - brave heart - 宮崎歩.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: " 宮崎歩",
    time: "04:12",
    des: "每次听到这里，心里那个小孩都会重新鼓起勇气。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "Hikari, Ideyo, Nanji Granzort（光啊，现身吧，格兰佐特！）",
    song_file: "光能使者 - Granzort.mp3",
    img_file: "光能使者 - Granzort.webp",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "田中公平",
    time: "02:52",
    des: "旋律一出来，小时候守在电视机前的黄昏又亮了起来。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "生命的云彩《憨八龟的故事》",
    song_file: "生命的云彩 - 沸点乐队.mp3",
    img_file: "生命的云彩 - 沸点乐队.jpg",
    lyrics_file: "生命的云彩 - 沸点乐队.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "沸点乐队",
    time: "02:15",
    des: "最治愈的童年歌，总像有人轻轻提醒你：别把天真弄丢了。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "青鸟《火影忍者》",
    song_file: "青鸟（《火影忍者》主题曲） - Ellie方紫薇.mp3",
    img_file: "青鸟（《火影忍者》主题曲） - Ellie方紫薇.jpg",
    lyrics_file: "青鸟（《火影忍者》主题曲） - Ellie方紫薇.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Ellie",
    time: "03:36",
    des: "每次听到副歌，都像有人把少年时的热血重新塞回胸口。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "一个师傅仨徒弟",
    song_file: "一个师傅仨徒弟 - 吸引力合唱组.mp3",
    img_file: "一个师傅仨徒弟 - 吸引力合唱组.jpg",
    lyrics_file: "一个师傅仨徒弟 - 吸引力合唱组.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "吸引力合唱组",
    time: "02:11",
    des: "一路降妖的热闹和童年滤镜，全在这几句熟悉的旋律里。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "魔訶不思議アドベンチャー!（摩诃不可思议大冒险）",
    song_file: "makafushigi-adventure - hiroki-takahashi.mp3",
    img_file: "makafushigi-adventure - hiroki-takahashi.jpg",
    lyrics_file: "makafushigi-adventure - hiroki-takahashi.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "高橋洋樹",
    time: "03:53",
    des: "《龙珠》最初的冒险号角，一开口就是筋斗云、龙珠和那个停不下来的少年时代。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_DONGMANYINGSHI,
    song_name: "ロマンティックあげるよ（把浪漫送给你）",
    song_file: "romantic-ageru-yo - ushio-hashimoto.mp3",
    img_file: "romantic-ageru-yo - ushio-hashimoto.jpg",
    lyrics_file: "romantic-ageru-yo - ushio-hashimoto.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "橋本潮",
    time: "03:50",
    des: "温柔又俏皮的片尾曲，把热血冒险后的浪漫和不舍都轻轻收进旋律里。",
  }
];
