import { CONFIG } from '../app/config.js';

const TYPE = "怀旧金曲";
const FILE_MUSIC_HUAIJIUJINQV = "huaijiujinqv/";

export const nostalgiaList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "大海 - 张雨生",
    song_file: "大海 - 张雨生.mp3",
    img_file: "  ",
    lyrics_file: "大海 - 张雨生.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张雨生",
    time: "04:40",
    des: "你是我这辈子跨不过去的大海，无论我在岸上喊得多用力，你都不会再回应了。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "星星点灯 - 郑智化",
    song_file: "星星点灯 - 郑智化.mp3",
    img_file: "  ",
    lyrics_file: "星星点灯 - 郑智化.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "郑智化",
    time: "05:00",
    des: "黑暗并不可怕，可怕的是忘了抬头看看那盏属于自己的灯。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "老鼠爱大米 - 杨臣刚",
    song_file: "老鼠爱大米 - 杨臣刚.mp3",
    img_file: "  ",
    lyrics_file: "老鼠爱大米 - 香香.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "杨臣刚",
    time: "05:04",
    des: "今天语文老师教我们文言文中\"之\"的取独用法，以本歌经典歌词为例，翻译成了古汉语：\"吾之爱汝，如鼠之爱粟。\"简直印象不能再深刻[大哭][大哭][大哭]",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "老鼠爱大米 - 香香",
    song_file: "老鼠爱大米 - 香香.mp3",
    img_file: "  ",
    lyrics_file: "老鼠爱大米 - 香香.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "香香",
    time: "05:01",
    des: "今天语文老师教我们文言文中\"之\"的取独用法，以本歌经典歌词为例，翻译成了古汉语：\"吾之爱汝，如鼠之爱粟。\"简直印象不能再深刻[大哭][大哭][大哭]",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "美人吟 - 李玲玉",
    song_file: "美人吟 - 李玲玉.mp3",
    img_file: "美人吟 - 李玲玉.jpg",
    lyrics_file: "美人吟 - 李玲玉.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李玲玉",
    time: "04:02",
    des: "舒畅。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "雨花石（电视连续剧《红红的雨花石》主题歌）",
    song_file: "雨花石（电视连续剧《红红的雨花石》主题歌）.mp3",
    img_file: " ",
    lyrics_file: "雨花石（电视连续剧《红红的雨花石》主题歌）.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈每文、熊健萍、陈帆等",
    time: "03:49",
    des: "我是一颗小小的石头",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "北郊 - 迟志强",
    song_file: "北郊 - 迟志强.mp3",
    img_file: "",
    lyrics_file: "北郊 - 迟志强.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: "05:05",
    des: "如果当时",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "铁窗泪 - 迟志强",
    song_file: "铁窗泪 - 迟志强.mp3",
    img_file: "铁窗泪 - 迟志强.webp",
    lyrics_file: "铁窗泪 - 迟志强.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: "08:27",
    des: "铁窗关住的是年月，关不住一个人回头看人生的叹息。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "钞票 - 迟志强",
    song_file: "钞票 - 迟志强.mp3",
    img_file: "",
    lyrics_file: "钞票 - 迟志强.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: "03:09",
    des: "小时候听的是调侃，长大后才知道每一句都扎在生活里。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "愁啊愁 - 迟志强",
    song_file: "愁啊愁 - 迟志强.mp3",
    img_file: "",
    lyrics_file: "愁啊愁 - 迟志强.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: "04:43",
    des: "愁到深处反而唱得直白，像老朋友把苦水一口气倒完。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "狱中十二月 - 迟志强",
    song_file: "狱中十二月 - 迟志强.mp3",
    img_file: "狱中十二月 - 迟志强.webp",
    lyrics_file: "狱中十二月 - 迟志强.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: "03:07",
    des: "把一年唱成十二个月的想家，听到最后只剩一声叹息。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "打工十二月 - 翟惠民",
    song_file: "打工十二月 - 翟惠民.mp3",
    img_file: "打工十二月 - 翟惠民.jpg",
    lyrics_file: "打工十二月 - 翟惠民.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "翟惠民",
    time: "06:08",
    des: "为了生活奔波的人，最懂这首歌里那种又累又不肯倒下。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "流浪歌 - 迟志强",
    song_file: "流浪歌 - 迟志强.mp3",
    img_file: "流浪歌 - 迟志强.webp",
    lyrics_file: "流浪歌 - 迟志强.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "迟志强",
    time: "04:57",
    des: "流浪不是没有方向，是心里总有个回不去的地方。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "吻别 - 张学友",
    song_file: "吻别 - 张学友.mp3",
    img_file: "吻别 - 张学友.jpg",
    lyrics_file: "吻别 - 张学友.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张学友",
    time: "05:02",
    des: "有些告别唱出来很轻，落在心里却很重。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "江南 - 林俊杰",
    song_file: "江南 - 林俊杰.mp3",
    img_file: "江南 - 林俊杰.jpg",
    lyrics_file: "江南 - 林俊杰.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "林俊杰",
    time: "04:28",
    des: "一场烟雨，一段放不下的旧梦。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "满江红",
    song_file: "满江红 - 刘可.mp3",
    img_file: "满江红 - 刘可.jpg",
    lyrics_file: "满江红 - 刘可.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "刘可",
    time: "03:11",
    des: "听到的是一腔热血，也是普通人心里那点不肯低头的劲。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "滚滚长江东逝水",
    song_file: "滚滚长江东逝水 - 杨洪基.mp3",
    img_file: "./assets/covers/defaults/53.jpg",
    lyrics_file: "滚滚长江东逝水 - 杨洪基.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "杨洪基",
    time: "02:58",
    des: "一开口就是历史的江水，英雄成败都被浪花慢慢带远。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "铁血丹心",
    song_file: "铁血丹心 - 罗文.mp3",
    img_file: "铁血丹心 - 罗文.jpg",
    lyrics_file: "铁血丹心 - 罗文.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "罗文",
    time: "02:54",
    des: "家国、江湖与儿女情长，都在这股豪气里烧得滚烫。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "上海滩",
    song_file: "上海滩 - 叶丽仪.mp3",
    img_file: "上海滩 - 叶丽仪.jpg",
    lyrics_file: "上海滩 - 叶丽仪.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "叶丽仪",
    time: "03:14",
    des: "风浪、霓虹和旧时代的恩怨，一起卷进那声苍茫的开场。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "世间始终你好",
    song_file: "世间始终你好 - 罗文.mp3",
    img_file: "世间始终你好 - 罗文.jpg",
    lyrics_file: "世间始终你好 - 罗文.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "罗文",
    time: "02:47",
    des: "江湖路远，最难忘的还是并肩看过风雨的人。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "难念的经",
    song_file: "难念的经 - 周华健.mp3",
    img_file: "难念的经 - 周华健.jpg",
    lyrics_file: "难念的经 - 周华健.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "周华健",
    time: "04:48",
    des: "唱的是红尘里的执念，越快越像命运追着人奔跑。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "沧海一声笑",
    song_file: "沧海一声笑 - 许冠杰.mp3",
    img_file: "沧海一声笑 - 许冠杰.jpg",
    lyrics_file: "沧海一声笑 - 许冠杰.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "许冠杰",
    time: "02:55",
    des: "把恩怨交给江湖，把洒脱留给一声大笑。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_HUAIJIUJINQV,
    song_name: "爱江山更爱美人",
    song_file: "爱江山更爱美人 - 李丽芬.mp3",
    img_file: "爱江山更爱美人 - 李丽芬.jpg",
    lyrics_file: "爱江山更爱美人 - 李丽芬.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李丽芬",
    time: "05:18",
    des: "江湖再大，也抵不过心里那个想一起看尽繁华的人。",
  },
];
