import { CONFIG } from '../app/config.js';

const TYPE = "节奏律动";
const FILE_MUSIC_JIEZOULVDONG = "jiezoulvdong/";
const FILE_MUSIC_SHISHIPEIYUE = "shishipeiyue/";

export const rhythmList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Fade",
    song_file: "Fade - Alan Walker.mp3",
    img_file: "Fade - Alan Walker.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Alan Walker",
    time: "04:24",
    des: "跑起来吧",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Something Just Like This",
    song_file: "Something Just Like This - The Chainsmokers,Coldplay.mp3",
    img_file: "Something Just Like This - The Chainsmokers,Coldplay.jpg",
    lyrics_file: "Something Just Like This - The Chainsmokers,Coldplay.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "The Chainsmokers,Coldplay",
    time: "04:07",
    des: "喜欢iPad你就去买，喜欢莱卡你就去赚，想喝港式奶茶你就过口岸，想当team leader你就努力学习然后努力去工作，想去威尼斯你就攒钱去，想爱谁你就去爱，想追谁你就去追，想到了就去做，拼命努力，拼命享受，忍着守着惦记着，青春就过去了，何必用40岁的心态过20岁的年华。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Reality",
    song_file: "Reality - Lost Frequencies.mp3",
    img_file: "Reality - Lost Frequencies.jpg",
    lyrics_file: "Reality - Lost Frequencies.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Lost Frequencies",
    time: "02:39",
    des: "轻快旋律里有远行的风，适合把烦恼暂时留在身后。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Sing Me to Sleep",
    song_file: "Sing Me to Sleep - Alan Walker.mp3",
    img_file: "Sing Me to Sleep - Alan Walker.jpg",
    lyrics_file: "Sing Me to Sleep - Alan Walker.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Alan Walker",
    time: "03:07",
    des: "像夜晚慢慢合上眼，把疲惫交给温柔的节奏。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Dance Monkey",
    song_file: "Dance Monkey - Tones and I.mp3",
    img_file: "Dance Monkey - Tones and I.jpg",
    lyrics_file: "Dance Monkey - Tones and I.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Tones and I",
    time: "03:29",
    des: "I'm a dance monkey, I'm a dance monkey, I'm a dance monkey.",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Believer",
    song_file: "Believer - Imagine Dragons.mp3",
    img_file: "Believer - Imagine Dragons.jpg",
    lyrics_file: "Believer - Imagine Dragons.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Imagine Dragons",
    time: "03:39",
    des: "疼痛没有把人打倒，反而把心里的鼓点敲得更响。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "The Spectre",
    song_file: "The Spectre - Alan Walker.mp3",
    img_file: "The Spectre - Alan Walker.jpg",
    lyrics_file: "The Spectre - Alan Walker.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Alan Walker",
    time: "03:13",
    des: "电子节拍像夜色里的光，越走越有不回头的力量。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "We Are Electric",
    song_file: "We Are Electric - Flying Steps.mp3",
    img_file: "We Are Electric - Flying Steps.jpg",
    lyrics_file: "We Are Electric - Flying Steps.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Flying Steps",
    time: "03:28",
    des: "节拍一亮起来，整个人像被城市夜色重新充满了电。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Gentleman",
    song_file: "Gentleman - PSY.mp3",
    img_file: "Gentleman - PSY.jpg",
    lyrics_file: "Gentleman - PSY.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "PSY",
    time: "03:15",
    des: "玩世不恭的律动一响，整个人都被拉进舞池中央。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "Gangnam Style (강남스타일)",
    song_file: "gangnam-style - psy.mp3",
    img_file: "gangnam-style - psy.jpg",
    lyrics_file: "gangnam-style - psy.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "PSY",
    time: "03:39",
    des: "这首歌自带派对开关，前奏一响就很难保持严肃。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_JIEZOULVDONG,
    song_name: "보여줄게 （给你看）",
    song_file: "boyeojulge - ailee.mp3",
    img_file: "boyeojulge - ailee.jpg",
    lyrics_file: "boyeojulge - ailee.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Ailee",
    time: "03:53",
    des: "把眼泪唱成漂亮的反击，越到副歌越有重新发光的劲。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "亡灵序曲 (The Dawn)",
    song_file: "The Dawn_亡灵序曲.mp3",
    img_file: "The Dawn_亡灵序曲.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Dreamtale",
    time: "04:06",
    des: "《The Dawn》的原意为黎明、拂晓、破晓，但在国内网络上，广被讹传为\"亡灵序曲\"。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "伊卡洛斯 Icarus",
    song_file: "icarus.mp3",
    img_file: "icarus.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Ivan Torrent",
    time: "04:35",
    des: "Ivan Torrent 是西班牙一个独立作曲家和制作人。为流行音乐和舞蹈艺术家在西班牙工作多年，作为一个设计师，也为广播电台做广告宣传和广告歌曲。现在Ivan Torrent想更专注于电影音乐的场景，为预告片音乐公司工作，以及做演示样品库。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Heart of Courage",
    song_file: "Heart of Courage - Two Steps From Hell.mp3",
    img_file: "Heart of Courage - Two Steps From Hell.jpg",
    lyrics_file: "Heart of Courage - Two Steps From Hell.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Two Steps From Hell",
    time: "01:57",
    des: "真正的勇气不是不害怕，而是害怕的时候还愿意往前一步。",
  },
    {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Victory",
    song_file: "Victory (Orchestral) - Two Steps From Hell.mp3",
    img_file: "Victory (Orchestral) - Two Steps From Hell.jpg",
    lyrics_file: "Victory (Orchestral) - Two Steps From Hell.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Two Steps From Hell",
    time: "05:22",
    des: "这首一响，连失败过的自己都想重新站起来一次。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Time",
    song_file: "Time - Hans Zimmer.mp3",
    img_file: "Time - Hans Zimmer.jpg",
    lyrics_file: "Time - Hans Zimmer.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Hans Zimmer",
    time: "04:35",
    des: "时间最温柔也最残忍，它带走很多东西，也留下我们成为现在的自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Breath and Life",
    song_file: "Breath And Life - Audiomachine.mp3",
    img_file: "Breath And Life - Audiomachine.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Audiomachine",
    time: "01:48",
    des: "像第一束光穿过云层，提醒人活着本身就是一场盛大的远行。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Electric Romeo",
    song_file: "Electric Romeo - Immediate Music.mp3",
    img_file: "Electric Romeo - Immediate Music.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Immediate Music",
    time: "02:28",
    des: "浪漫被鼓点点燃，像一场明知危险却仍要奔赴的梦。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Experience - Ludovico Einaudi",
    song_file: "Experience - Ludovico Einaudi.mp3",
    img_file: "Experience - Ludovico Einaudi.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Ludovico Einaudi",
    time: "05:16",
    des: "越安静的旋律越有力量，它不推你流泪，只陪你把情绪走完。",
  }
];
