import { CONFIG } from '../app/config.js';

const TYPE = "流行经典";
const FILE_MUSIC_LIUXINGJINGDIAN = "liuxingjingdian/";

export const popClassicsList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "夜空中最亮的星 - 逃跑计划",
    song_file: "夜空中最亮的星 - 逃跑计划.mp3",
    img_file: "  ",
    lyrics_file: "夜空中最亮的星 - 逃跑计划.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "逃跑计划",
    time: "04:12",
    des: "黑暗多的时候，我就抬头找光。不是为了看得更远，而是为了让自己不倒下。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "水木年华 - 一生有你",
    song_file: "水木年华 - 一生有你.mp3",
    img_file: "  ",
    lyrics_file: "一生有你.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "水木年华",
    time: "04:18",
    des: "此生未曾拥有。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "陈一发儿 - 童话镇",
    song_file: "陈一发儿 - 童话镇.mp3",
    img_file: "  ",
    lyrics_file: "童话镇.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈一发儿",
    time: "04:18",
    des: "沉浸在童话的世界里不愿醒来。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "奇妙能力歌 - 陈粒",
    song_file: "奇妙能力歌 - 陈粒.mp3",
    img_file: "  ",
    lyrics_file: "奇妙能力歌.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈粒",
    time: "04:13",
    des: "我听过一万首歌，看过一千部电影，读过一百本书，却从未俘获一个人的心。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "此生不换",
    song_file: "此生不换 - 青鸟飞鱼.mp3",
    img_file: "此生不换.jpg",
    lyrics_file: "此生不换.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "青鸟飞鱼",
    time: "04:25",
    des: "在初中暗恋三年的同桌，有一天看见她在折星星，\n我问她，这是送给谁的啊，她说，送给她最爱的人，\n过了几天，她送了个熊娃娃给我，我在想，那些星星她是送给谁的?\n过了很多年，我结婚了，生了孩子，把熊给孩子玩，\n一天，孩子不小心把熊撕破了，一大把的星星掉了出来，我顿时泪目。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "断点",
    song_file: "断点.mp3",
    img_file: "断点.jpg",
    lyrics_file: "断点.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张敬轩",
    time: "04:28",
    des: "其实我挺羡慕火车的。 \n  为什么? \n 他们连擦肩而过都那么久。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "天顶一粒星 - Tizzy T,宋佳",
    song_file: "天顶一粒星 - Tizzy T,宋佳.mp3",
    img_file: "9.jpg",
    lyrics_file: "天顶一粒星.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Tizzy T,宋佳",
    time: "03:53",
    des: "嘿呀嘿呀咿儿呀",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "仙剑问情(主题曲) - 萧人凤",
    song_file: "仙剑问情(主题曲) - 萧人凤.mp3",
    img_file: "仙剑问情(主题曲) - 萧人凤.jpg",
    lyrics_file: "仙剑问情.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "萧人凤",
    time: "04:16",
    des: "我李逍遥可以对天发誓从今以后不会再让你一人孤苦伶仃。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "唯一-告五人",
    song_file: "唯一-告五人.MP3",
    img_file: " ",
    lyrics_file: "唯一.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "告五人",
    time: "04:31",
    des: "我一直很清楚，喜欢你这件事，从来没办法平均分给别人。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "不浪漫罪名-王杰",
    song_file: "不浪漫罪名-王杰.MP3",
    img_file: " ",
    lyrics_file: "不浪漫罪名.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "王杰",
    time: "04:43",
    des: "我犯下了滔天的罪名",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "明天，你好 - 牛奶咖啡",
    song_file: "明天，你好 - 牛奶咖啡.mp3",
    img_file: " ",
    lyrics_file: "明天，你好 - 牛奶咖啡.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "牛奶咖啡",
    time: "04:31",
    des: "今天的你也许很累，但请相信——明天的风，会比今天温柔一点。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "那些花儿 - 朴树",
    song_file: "那些花儿 - 朴树.mp3",
    img_file: " ",
    lyrics_file: "那些花儿 - 朴树.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "朴树",
    time: "04:55",
    des: "那些走丢的人，那些开过的花，都住在我心里最柔软的地方。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "绿光 - 孙燕姿",
    song_file: "绿光 - 孙燕姿.mp3",
    img_file: " ",
    lyrics_file: "绿光 - 孙燕姿.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "孙燕姿",
    time: "03:11",
    des: "我想超越这平凡的生活，注定现在暂时漂泊。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "我怀念的 - 孙燕姿",
    song_file: "我怀念的 - 孙燕姿.mp3",
    img_file: " ",
    lyrics_file: "我怀念的 - 孙燕姿.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "孙燕姿",
    time: "04:50",
    des: "我怀念的，是什么？",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "七里香 - 周杰伦",
    song_file: "七里香 - 周杰伦.mp3",
    img_file: " ",
    lyrics_file: "七里香 - 周杰伦.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "周杰伦",
    time: "04:59",
    des: "窗外的麻雀在电线杆上多嘴，你说这一句很有夏天的感觉。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "My Heart Will Go On (Love Theme from _Titanic_)",
    song_file: "My Heart Will Go On (Love Theme from _Titanic_).mp3",
    img_file: " ",
    lyrics_file: "My Heart Will Go On (Love Theme from _Titanic_).lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Celine Dion",
    time: "05:10",
    des: "我心永恒",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "传奇 - 李健",
    song_file: "传奇 - 李健.mp3",
    img_file: " ",
    lyrics_file: "传奇 - 李健.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李健",
    time: "05:24",
    des: "只是因为在人群中多看了你一眼，再也没能忘掉你容颜。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "倩女幽魂 - 张国荣",
    song_file: "倩女幽魂 - 张国荣.mp3",
    img_file: " ",
    lyrics_file: "倩女幽魂 - 张国荣.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张国荣",
    time: "03:37",
    des: "倩女幽魂，倩女幽魂。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "九儿 - 胡莎莎",
    song_file: "九儿 - 胡莎莎.mp3",
    img_file: "九儿.jpg",
    lyrics_file: "九儿 - 胡莎莎.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "胡莎莎",
    time: "02:28",
    des: "一声九儿，唱出来的是土地、命运和一个人倔强的时光。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "Lonely - Nana",
    song_file: "Lonely - Nana.mp3",
    img_file: "Lonely - Nana.jpg",
    lyrics_file: "Lonely - Nana.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Nana",
    time: "06:21",
    des: "孤独不是没人陪，是热闹散场后还要自己和自己说晚安。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "旅行 - 许巍",
    song_file: "旅行 - 许巍.mp3",
    img_file: "旅行 - 许巍.jpg",
    lyrics_file: "旅行 - 许巍.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "许巍",
    time: "04:26",
    des: "许巍的歌总让人想出发，哪怕只是从疲惫里走出去一点。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "真的爱你 - BEYOND",
    song_file: "真的爱你 - BEYOND.mp3",
    img_file: "真的爱你 - BEYOND.webp",
    lyrics_file: "真的爱你 - BEYOND.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: "04:35",
    des: "这首歌不是唱给母亲听的，是唱给每个终于懂事的孩子听的。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "情人 - BEYOND",
    song_file: "情人_Beyond.mp3",
    img_file: "情人_Beyond.jpg",
    lyrics_file: "情人_Beyond.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: "05:18",
    des: "情人，情人，情人。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "光辉岁月 - BEYOND",
    song_file: "光辉岁月 - BEYOND.mp3",
    img_file: "光辉岁月 - BEYOND.webp",
    lyrics_file: "光辉岁月 - BEYOND.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: "05:02",
    des: "真正的光辉不是没有黑暗，而是在黑暗里还愿意相信人。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "喜欢你 - BEYOND",
    song_file: "喜欢你 - BEYOND.mp3",
    img_file: "喜欢你 - BEYOND.webp",
    lyrics_file: "喜欢你 - BEYOND.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: "04:34",
    des: "一句喜欢你，藏着多少少年时代说不出口的认真。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "海阔天空 - BEYOND",
    song_file: "海阔天空 - BEYOND.mp3",
    img_file: "海阔天空 - BEYOND.webp",
    lyrics_file: "海阔天空 - BEYOND.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: "05:25",
    des: "每个不肯低头的人，心里大概都有一片自己的海阔天空。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "灰色轨迹 - BEYOND",
    song_file: "灰色轨迹 - Beyond.mp3",
    img_file: "灰色轨迹 - Beyond.jpg",
    lyrics_file: "灰色轨迹 - Beyond.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: "05:25",
    des: "灰色的不是轨迹，是走过青春后再回头看的沉默。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "Dream It Possible - Delacey",
    song_file: "Dream It Possible - Delacey.mp3",
    img_file: "1.jpg",
    lyrics_file: "Dream It Possible.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Delacey",
    time: "03:24",
    des: "不用等梦想成真，只要每天做一点点。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "挪威的森林 - 伍佰",
    song_file: "挪威的森林 - 伍佰.mp3",
    img_file: "挪威的森林 - 伍佰.jpg",
    lyrics_file: "挪威的森林.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "伍佰",
    time: "06:33",
    des: "心中是否有我未曾到过的地方啊",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "追梦赤子心 - GALA",
    song_file: "追梦赤子心 - GALA.mp3",
    img_file: "追梦赤子心 - GALA.jpg",
    lyrics_file: "追梦赤子心 - GALA.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "GALA",
    time: "05:18",
    des: "愿你被现实按倒很多次，仍然能像第一次那样爬起来追梦。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_LIUXINGJINGDIAN,
    song_name: "大地 - BEYOND",
    song_file: "大地 - BEYOND.mp3",
    img_file: "大地 - BEYOND.webp",
    lyrics_file: "大地 - BEYOND.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "BEYOND",
    time: "04:11",
    des: "真正有重量的歌，不是喊得多高，而是多年以后再听，心里还是会微微一震。",
  }
];
