import { CONFIG } from '../app/config.js';

const TYPE = "民谣";
const FILE_MUSIC_MINYAO = "minyao/";

export const folkList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "安和桥 - 宋冬野",
    song_file: "安和桥 - 宋冬野.mp3",
    img_file: "",
    lyrics_file: "安和桥 - 宋冬野.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宋冬野",
    time: "04:10",
    des: "村东头的狗都懂了遗憾的意义",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "斑马，斑马 - 宋冬野",
    song_file: "斑马，斑马 - 宋冬野.mp3",
    img_file: "",
    lyrics_file: "斑马，斑马 - 宋冬野.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宋冬野",
    time: "04:14",
    des: "世界如此广阔，人类却走进了悲伤的墙角。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "成都 - 赵雷",
    song_file: "成都 - 赵雷.mp3",
    img_file: "",
    lyrics_file: "成都 - 赵雷.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: "05:29",
    des: "我在这座城市听《成都》，它就变成了我的故事。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "春风十里 - 鹿先森乐队",
    song_file: "春风十里 - 鹿先森乐队.mp3",
    img_file: "",
    lyrics_file: "春风十里 - 鹿先森乐队.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "鹿先森乐队",
    time: "06:15",
    des: "不如遇见你。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "董小姐 - 宋冬野",
    song_file: "董小姐 - 宋冬野.mp3",
    img_file: "",
    lyrics_file: "董小姐 - 宋冬野.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宋冬野",
    time: "05:10",
    des: "求给陌生人一支兰州，我已经付了零钱和敬意。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "鼓楼 - 赵雷",
    song_file: "鼓楼 - 赵雷.mp3",
    img_file: "",
    lyrics_file: "鼓楼 - 赵雷.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: "04:41",
    des: "城市太大了，大到装得下所有烦恼，却装不下一个想拥抱的人。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "理想三旬 - 陈鸿宇",
    song_file: "理想三旬 - 陈鸿宇.mp3",
    img_file: "理想三旬 - 陈鸿宇.jpg",
    lyrics_file: "理想三旬 - 陈鸿宇.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈鸿宇",
    time: "03:30",
    des: "曾以为理想三旬，只是个诗意的词，后来才知道——是我们终究要长大的意思。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "南方姑娘 - 赵雷",
    song_file: "南方姑娘 - 赵雷.mp3",
    img_file: "",
    lyrics_file: "南方姑娘 - 赵雷.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: "05:32",
    des: "我会去南方么？我问我自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "白桦林 - 朴树",
    song_file: "白桦林 - 朴树.mp3",
    img_file: "",
    lyrics_file: "白桦林 - 朴树.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "朴树",
    time: "03:47",
    des: "最让人难受的不是他死在白桦林里，而是她永远不知道。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "我们的时光 - 赵雷",
    song_file: "我们的时光 - 赵雷.mp3",
    img_file: "我们的时光 - 赵雷.jpg",
    lyrics_file: "我们的时光 - 赵雷.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "赵雷",
    time: "04:30",
    des: "我们的时光，我们的时光，我们的时光，我们的时光。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "南山南 - 马頔",
    song_file: "南山南 - 马頔.mp3",
    img_file: "南山南 - 马頔.jpg",
    lyrics_file: "南山南 - 马頔.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "马頔",
    time: "05:23",
    des: "南山南，北秋悲，南山有谷堆，南风喃，北海北，北海有墓碑。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "写给黄淮 - 邵帅",
    song_file: "写给黄淮 - 邵帅.mp3",
    img_file: "写给黄淮 - 邵帅.jpg",
    lyrics_file: "写给黄淮 - 邵帅.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "邵帅",
    time: "04:01",
    des: "写给黄淮，我们的时光，我们的时光，我们的时光。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "七月上 - Jam",
    song_file: "七月上 - Jam.mp3",
    img_file: "七月上 - Jam.jpg",
    lyrics_file: "七月上 - Jam.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Jam",
    time: "03:10",
    des: "我像个傻子一样记住了你。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "余香 - 张小九",
    song_file: "余香 - 张小九.mp3",
    img_file: "余香 - 张小九.jpg",
    lyrics_file: "余香 - 张小九.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张小九 ",
    time: "04:06",
    des: "余香，我们的时光，我们的时光，我们的时光。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_MINYAO,
    song_name: "云烟成雨 - 房东的猫",
    song_file: "云烟成雨 - 房东的猫.mp3",
    img_file: "云烟成雨 - 房东的猫.jpg",
    lyrics_file: "云烟成雨 - 房东的猫.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "房东的猫",
    time: "04:00",
    des: "想念像云烟，落下来是雨，散开了还是你。",
  }
];
