import { CONFIG } from '../app/config.js';

const TYPE = "轻音乐";
const FILE_MUSIC_QINGYINYUE = "qingyinyue/";

export const lightMusicList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "天籁排箫 老鹰之歌 (El Condor Pasa)",
    song_file: "天籁排箫 老鹰之歌.mp3",
    img_file: "leo_rojas.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Leo Rojas",
    time: "03:36",
    des: "每次一听这深邃、高远的旋律，如雄鹰翱翔在蓝天，悠然自在，每个吹奏的音符敲击心怀，释放自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "Caribbean Blue - Enya",
    song_file: "Caribbean Blue - Enya.mp3",
    img_file: "Caribbean Blue - Enya.jpg",
    lyrics_file: "Caribbean Blue - Enya.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Enya",
    time: "03:58",
    des: "像海风吹过蓝色梦境，听完心里会安静很久。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "纯净如圣诗《Ide Were Were》",
    song_file: "纯净如圣诗.mp3",
    img_file: "music_ide.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Deva Premal",
    time: "07:59",
    des: "天人合一的自然美感。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "兰花草 (天籁般的哼唱) - 卡洛儿",
    song_file: "兰花草.mp3",
    img_file: "卡洛儿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "卡洛儿",
    time: "04:19",
    des: "兰花草的香，兰花草的甜，我种兰花草，只待故人归，哪怕春去秋过冬又来。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "莫尔德颂歌 (Molde Canticle) - Sissel",
    song_file: "莫尔德颂歌.mp3",
    img_file: "莫尔德颂歌.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Sissel",
    time: "03:26",
    des: "一首空灵清澈令人感动令人着迷的天籁吟唱 \n 唯美的旋律，迷人的天籁，如空谷的风轻柔不羁，空灵清澈地吟唱着美丽与哀愁，让人怀想起那些曾经青涩而纯真的画面。 \n西丝尔(Sissel Kyrkjebo)挪威著名的女歌手，正如电影《泰坦尼克》配乐中那幽幽天籁，其歌声总能抚慰感伤的心绪。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "斯卡布罗集市 (Scarborough Fair) - 卡洛儿",
    song_file: "斯卡布罗集市.mp3",
    img_file: "卡洛儿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "卡洛儿",
    time: "04:24",
    des: "完美的女声吟唱。选自卡洛儿《一尘不染》",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "斯卡布罗集市 - Sarah Brightman",
    song_file: "斯卡布罗集市 - Sarah Brightman.mp3",
    img_file: "Simon & Garfunkel.jpeg",
    lyrics_file: "斯卡布罗集市.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "莎拉·布莱曼",
    time: "04:16",
    des: "《斯卡布罗集市》仿佛在倾诉什么，细雨敲窗的秋夜，她的倾诉，能把你带进逝去的情感伤痛中，回味曾经拥有的凄美的爱恋；\n心情烦躁的时候，她的倾诉，能把你带进寂静山林的深处，静坐在纯洁净美的幽谷里冷却自我；\n春风得意的时候，她的倾诉，能把你带进空灵梦幻苍穹里，感受并憧憬充满希望未来人生。\n总之，无论何时何地，《斯卡布罗集市》的天籁之声能陪你的心灵一起悲欢、一同祈祷……",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "我的歌声里-钢琴曲",
    song_file: "我的歌声里-钢琴曲.mp3",
    img_file: "我的歌声里.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "赵海洋",
    time: "03:29",
    des: "你没有办法在这个忘却的世间用声音来将谁记得\n回忆过了期\n你已不再年少\n病态\n焦躁\n彷徨还有不安\n尽管是这样不堪的我\n仍想牵着你的手\n拼尽整个青春\n与你一同到天涯\n她在我的梦里。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "残月（排箫）芈月传 - 王备",
    song_file: "西风（排箫）.mp3",
    img_file: "西风.png",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "王备",
    time: "05:04",
    des: "一曲琴韵瑟瑟，悲欢尘世离合。\n醮一抹沧桑，盈满袖暗香，将尘俗情思泯于无痕。\n在指间舞落一世繁华，弹尽一曲浪漫忧伤。\n掮一轮皓月，携一缕清风，穿越千年尘烟。\n寂寞纤指滑过灵魂的忧伤，多少深情未了。\n多少笑泪飞扬，蓦然回首，惘然一梦，\n惘然回顾中，却早已遗失了你。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "一叶子 - 林键标",
    song_file: "一叶子 - 林键标.mp3",
    img_file: "一叶子.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "林键标",
    time: "03:16",
    des: "独孤轻吟",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "秋日私语 - Richard Clayderman",
    song_file: "秋日私语 - Richard Clayderman.mp3",
    img_file: "15.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Richard Clayderman",
    time: "03:22",
    des: "那日的午后",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "寂静的天空 (来自草原的寂静天籁) - 代青塔娜",
    song_file: "寂静的天空 (来自草原的寂静天籁) - 代青塔娜.mp3",
    img_file: " ",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "代青塔娜",
    time: "06:05",
    des: "在那风吹的草原\n有我心上的人\n风啊 你轻轻吹\n听他忧伤的歌\n月亮啊 你照亮他\n火光啊 你温暖他\n在那遥远的天空 有我思念的云\n夜莺呀 你轻声和\n听我静静地唱\n云啊 飘向何方\n心啊 随好流浪",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "送别 (口琴伴奏版) - 群星",
    song_file: "送别 (口琴伴奏版) - 群星.mp3",
    img_file: " ",
    lyrics_file: "送别.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "群星",
    time: "04:54",
    des: "愿漂泊的人有酒喝，愿孤独的人会唱歌。\n往前走，别回头。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "call of silence",
    song_file: "call of silence.MP3",
    img_file: " ",
    lyrics_file: "call of silence.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "",
    time: "04:39",
    des: "成长不是变得坚强，是学会了什么都不说。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "天空之城 - 久石让",
    song_file: "天空之城 - 久石让.mp3",
    img_file: "天空之城 - 久石让.webp",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "久石让",
    time: "04:13",
    des: "不用歌词也能让人想哭，因为每个人心里都有一座回不去的城。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "時代を越える想い - 和田薫",
    song_file: "時代を越える想い - 和田薫.mp3",
    img_file: "時代を越える想い - 和田薫.webp",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "和田薫",
    time: "03:10",
    des: "像隔着很长的岁月回望，所有离别都被旋律轻轻放下。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "Illusionary Daytime(幻昼) - Shirfine",
    song_file: "Illusionary Daytime - Shirfine.mp3",
    img_file: "Illusionary Daytime - Shirfine.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Shirfine",
    time: "04:10",
    des: "适合一个人发呆的曲子，听着听着，白天也像做了一场梦。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "You - Approaching Nirvana",
    song_file: "You - Approaching Nirvana.mp3",
    img_file: "You - Approaching Nirvana.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Approaching Nirvana",
    time: "05:49",
    des: "这首曲子像把世界调成静音，只留下心跳和远方。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "Only Time - Enya",
    song_file: "Only Time - Enya.mp3",
    img_file: "Only Time - Enya.jpg",
    lyrics_file: "Only Time - Enya.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Enya",
    time: "03:38",
    des: "时间会带走很多东西，也会把真正放不下的留下来。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "净化心灵的声音 (Moon Temple) - Karunesh",
    song_file: "(Moon Temple) - Karunesh.mp3",
    img_file: "Moon Temple.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Karunesh",
    time: "05:49",
    des: "Moon Temple中文意为\"庙堂\"，Zen Breakfast意为 道禅 。我想，专辑名为《道禅》是希望每一个听者都能从这飘缈的音乐声中，对社会，对人生，对情感有所感悟吧！\n在纷乱的现实生活中，在复杂的情感世界里，每一个人都活的很累。于是，人们都在尝试着找寻一个不被人所窥视的空间，卸下沉重的包袱，让不堪负重的心灵得到稍许的休憩。就在这一刻，就在《Moon Temple》响起的时候，人性、道德、情感恢复到了本原。尤其是在在钢琴和萧声中，似乎又多了一个空灵的女声，她用温柔和声轻柔的抚摸着每一个听者的心灵创伤。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "思君黯然 - 陈国樑",
    song_file: "思君黯然 - 陈国樑.mp3",
    img_file: "16.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "陈国樑",
    time: "01:36",
    des: "可我还是在等你，哪怕只是在心里。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "思君黯然 二胡版",
    song_file: "思君黯然 二胡版.mp3",
    img_file: "16.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "浩然ERHU",
    time: "01:26",
    des: "阿朱 。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "雪见—仙凡之旅 - 麦振鸿",
    song_file: "雪见—仙凡之旅 - 麦振鸿.mp3",
    img_file: "雪见—仙凡之旅 - 麦振鸿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "麦振鸿",
    time: "04:50",
    des: "记得那个为爱掏心的红毛怪，有着无尽相思的夕瑶，等待千年的龙葵，为老大割肉的茂茂，假装背叛死无全尸的必平，纠缠了三生三世放不下的紫萱和徐长卿，还有那个用自己的命换天下人复活的景天，以思念幻化成型的雪见。都说景天负了夕瑶，只有夕瑶知道，景天不是飞蓬。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "共伴闯天涯 - 麦振鸿",
    song_file: "共伴闯天涯 - 麦振鸿.mp3",
    img_file: "共伴闯天涯 - 麦振鸿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "麦振鸿",
    time: "03:22",
    des: "你最心疼编剧给哪个角色写死了  \"——茂茂，我们到长安了！\"",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "Daughter of heaven - 段玫梅",
    song_file: "Daughter of heaven - 段玫梅.mp3",
    img_file: " ",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "段玫梅",
    time: "04:18",
    des: "她不是被命运选中的人，她是把命运握在手里的那个人。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "The Rain",
    song_file: "The Rain - 久石譲.mp3",
    img_file: "The Rain.jpg",
    lyrics_file: "The Rain - 久石譲.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "久石让",
    time: "05:39",
    des: "The Rain",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_QINGYINYUE,
    song_name: "River Flows In You",
    song_file: "River Flows In You - Martin Ermen.mp3",
    img_file: "River Flows In You - Martin Ermen.jpg",
    lyrics_file: "River Flows In You - Martin Ermen.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Martin Ermen",
    time: "03:18",
    des: "River Flows In You",
  }
];
