import { CONFIG } from '../app/config.js';

const TYPE = "伤感治愈";
const FILE_MUSIC_SHANGGANZHIYU = "shangganzhiyu/";

export const healingList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "那些年",
    song_file: "那些年 - 胡夏.mp3",
    img_file: "那些年 - 胡夏.jpg",
    lyrics_file: "那些年 - 胡夏.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "胡夏",
    time: "06:11",
    des: "青春最心酸的地方，就是回头看，每个瞬间都以为会永远。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "生日礼物",
    song_file: "生日礼物 - 江涛.mp3",
    img_file: "生日礼物 - 江涛.jpg",
    lyrics_file: "生日礼物 - 江涛.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "江涛",
    time: "04:28",
    des: "最怕礼物还在，送礼物的人已经走远。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "下雨天",
    song_file: "下雨天-南拳妈妈.MP3",
    img_file: "下雨天-南拳妈妈.jpg",
    lyrics_file: "下雨天-南拳妈妈.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "南拳妈妈",
    time: "04:13",
    des: "下雨天最适合想你，因为雨声刚好覆盖我所有没说出口的难过。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "有没有人告诉你",
    song_file: "有没有人告诉你 - 陈楚生.mp3",
    img_file: "有没有人告诉你 - 陈楚生.jpg",
    lyrics_file: "有没有人告诉你 - 陈楚生.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈楚生",
    time: "04:21",
    des: "我们之间再无交集。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "寂寞沙洲冷",
    song_file: "寂寞沙洲冷 - 周传雄.mp3",
    img_file: "寂寞沙洲冷 - 周传雄.jpg",
    lyrics_file: "寂寞沙洲冷 - 周传雄.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "周传雄",
    time: "04:37",
    des: "当记忆的线",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "我好想你",
    song_file: "我好想你-苏打绿.mp3",
    img_file: "我好想你-苏打绿.jpg",
    lyrics_file: "我好想你-苏打绿.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "苏打绿",
    time: "05:24",
    des: "这首歌每一句都像在替我说：我很好，也很想你，只是你不知道。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "烟火里的尘埃",
    song_file: "烟火里的尘埃 - 华晨宇.mp3",
    img_file: "烟火里的尘埃 - 华晨宇.jpg",
    lyrics_file: "烟火里的尘埃 - 华晨宇.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "华晨宇",
    time: "05:21",
    des: "我们都曾在热闹里显得渺小，却还是想被世界温柔看见。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "怎么说我不爱你",
    song_file: "怎么说我不爱你 - 萧敬腾.mp3",
    img_file: "怎么说我不爱你 - 萧敬腾.jpg",
    lyrics_file: "怎么说我不爱你 - 萧敬腾.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "萧敬腾",
    time: "04:35",
    des: "最怕的不是不爱了，是连解释爱过都显得多余。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "不要再来伤害我",
    song_file: "不要再来伤害我 - 张振宇.mp3",
    img_file: "不要再来伤害我 - 张振宇.jpg",
    lyrics_file: "不要再来伤害我 - 张振宇.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张振宇",
    time: "05:22",
    des: "有些歌听着像狠话，其实每一句都在替受伤的人求放过。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "杀破狼",
    song_file: "杀破狼—《仙剑奇侠传》主题曲 - 小念姑凉.mp3",
    img_file: "杀破狼—《仙剑奇侠传》主题曲 - 小念姑凉.jpg",
    lyrics_file: "杀破狼—《仙剑奇侠传》主题曲 - 小念姑凉.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "小念姑凉",
    time: "04:37",
    des: "宿命、离别和江湖都在这一声里铺开，像仙剑故事最锋利也最温柔的开场。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "生生世世爱",
    song_file: "生生世世爱 - 吴雨霏.mp3",
    img_file: "生生世世爱 - 吴雨霏.jpg",
    lyrics_file: "生生世世爱 - 吴雨霏.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "吴雨霏",
    time: "04:41",
    des: "我以为生生世世很长，可以慢慢等你。后来才懂，来日并不方长，喜欢的人也会走散。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "偏爱",
    song_file: "偏爱-张芸京.MP3",
    img_file: "偏爱-张芸京.jpg",
    lyrics_file: "偏爱-张芸京.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "张芸京",
    time: "03:33",
    des: "如此喜欢你的偏爱",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "此生不换",
    song_file: "此生不换 - 青鸟飞鱼.mp3",
    img_file: "此生不换 - 青鸟飞鱼.jpg",
    lyrics_file: "此生不换 - 青鸟飞鱼.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "青鸟飞鱼",
    time: "04:25",
    des: "在初中暗恋三年的同桌，有一天看见她在折星星，\n我问她，这是送给谁的啊，她说，送给她最爱的人，\n过了几天，她送了个熊娃娃给我，我在想，那些星星她是送给谁的?\n过了很多年，我结婚了，生了孩子，把熊给孩子玩，\n一天，孩子不小心把熊撕破了，一大把的星星掉了出来，我顿时泪目。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "一直很安静",
    song_file: "一直很安静-阿桑.MP3",
    img_file: "一直很安静-阿桑.jpg",
    lyrics_file: "一直很安静-阿桑.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "阿桑",
    time: "04:07",
    des: "有些心碎从来都没有声音，所以没人知道你有多难过。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "忘记时间",
    song_file: "忘记时间 - 胡歌.mp3",
    img_file: "忘记时间 - 胡歌.jpg",
    lyrics_file: "忘记时间 - 胡歌.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "胡歌",
    time: "04:32",
    des: "越想忘记，越会被某个瞬间带回从前；时间走远了，人却还停在旧梦里。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "雪见—仙凡之旅",
    song_file: "雪见—仙凡之旅 - 麦振鸿.mp3",
    img_file: "雪见—仙凡之旅 - 麦振鸿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "麦振鸿",
    time: "04:49",
    des: "记得那个为爱掏心的红毛怪，有着无尽相思的夕瑶，等待千年的龙葵，为老大割肉的茂茂，假装背叛死无全尸的必平，纠缠了三生三世放不下的紫萱和徐长卿，还有那个用自己的命换天下人复活的景天，以思念幻化成型的雪见。都说景天负了夕瑶，只有夕瑶知道，景天不是飞蓬。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "桃花岛-麦振鸿",
    song_file: "桃花岛-麦振鸿 - 麦振鸿.mp3",
    img_file: "桃花岛-麦振鸿 - 麦振鸿.jpg",
    lyrics_file: "桃花岛-麦振鸿 - 麦振鸿.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "麦振鸿",
    time: "03:54",
    des: "旋律一响，像桃花落进旧江湖，温柔、空灵，也带着一点回不去的怅然。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "莫失莫忘",
    song_file: "莫失莫忘（仙剑奇侠传一） - 葉湘倫.mp3",
    img_file: "莫失莫忘（仙剑奇侠传一） - 葉湘倫.jpg",
    lyrics_file: "莫失莫忘（仙剑奇侠传一） - 葉湘倫.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "葉湘倫",
    time: "03:34",
    des: "有些约定不用说出口，只要还记得，就像从未真正走散。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "共伴闯天涯",
    song_file: "共伴闯天涯 - 麦振鸿.mp3",
    img_file: "共伴闯天涯 - 麦振鸿.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "麦振鸿",
    time: "03:22",
    des: "你最心疼编剧给哪个角色写死了  \"——茂茂，我们到长安了！\"",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "水星记",
    song_file: "水星记 - 郭顶.mp3",
    img_file: "水星记 - 郭顶.jpg",
    lyrics_file: "水星记 - 郭顶.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "郭顶",
    time: "05:25",
    des: "最近的距离也可能隔着宇宙，温柔到让人不敢打扰。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "阿拉斯加海湾",
    song_file: "阿拉斯加海湾 - 蓝心羽.mp3",
    img_file: "阿拉斯加海湾 - 蓝心羽.jpg",
    lyrics_file: "阿拉斯加海湾 - 蓝心羽.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "蓝心羽",
    time: "04:01",
    des: "有些人像海湾，看起来很远，其实一直在心里涨潮。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "无人之岛",
    song_file: "无人之岛 - 任然.mp3",
    img_file: "无人之岛 - 任然.jpg",
    lyrics_file: "无人之岛 - 任然.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "任然",
    time: "04:45",
    des: "孤独像一座岛，潮水退去后才看见心里真正空着的地方。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "凄美地",
    song_file: "凄美地 - 郭顶.mp3",
    img_file: "凄美地 - 郭顶.jpg",
    lyrics_file: "凄美地 - 郭顶.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "郭顶",
    time: "04:10",
    des: "真正的告别不是转身，是突然听懂了这首歌的某一句。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "你从未离去",
    song_file: "你从未离去 - 白挺.mp3",
    img_file: "你从未离去 - 白挺.webp",
    lyrics_file: "你从未离去 - 白挺.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "白挺",
    time: "03:23",
    des: "真正重要的人不会离开，他只是住进了回忆最柔软的地方。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "卜卦",
    song_file: "卜卦 - 崔子格.mp3",
    img_file: "卜卦 - 崔子格.webp",
    lyrics_file: "卜卦 - 崔子格.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "崔子格",
    time: "03:36",
    des: "嘴上说随缘的人，心里其实早就把答案问了千百遍。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "离别开出花",
    song_file: "离别开出花 - 就是南方凯.mp3",
    img_file: "离别开出花 - 就是南方凯.jpg",
    lyrics_file: "离别开出花 - 就是南方凯.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "就是南方凯",
    time: "03:50",
    des: "把告别唱成成长，疼过以后也能开出一点光。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "悬溺",
    song_file: "悬溺 - 葛东琪.mp3",
    img_file: "悬溺 - 葛东琪.jpg",
    lyrics_file: "悬溺 - 葛东琪.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "葛东琪",
    time: "03:17",
    des: "爱像水面下的漩涡，越想挣脱越听见自己的心跳。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "悬溺",
    song_file: "悬溺 - 旺仔小乔.mp3",
    img_file: "悬溺 - 旺仔小乔.webp",
    lyrics_file: "悬溺 - 旺仔小乔.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "旺仔小乔",
    time: "03:17",
    des: "明知道会沉下去，还是舍不得松开那一点温柔。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "堕",
    song_file: "堕 - 旺仔小乔.mp3",
    img_file: "堕 - 旺仔小乔.webp",
    lyrics_file: "堕 - 旺仔小乔.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "旺仔小乔",
    time: "03:06",
    des: "爱不是突然坠落的，是从一点点心软开始的。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "海底",
    song_file: "海底 - 一支榴莲.mp3",
    img_file: "海底 - 一支榴莲.jpg",
    lyrics_file: "海底 - 一支榴莲.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "一支榴莲",
    time: "04:16",
    des: "有些难过像海底，没人看见，却压得人喘不过气。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "书房",
    song_file: "书房 - 顾君豪.mp3",
    img_file: "书房 - 顾君豪.jpg",
    lyrics_file: "书房 - 顾君豪.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "顾君豪",
    time: "04:52",
    des: "这种感觉真的很糟\n因为一句话就高兴半天\n发现了一件事就心凉半截\n喜欢不能太明显 不然不值钱",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "十一年",
    song_file: "十一年（翻自 邱永传） - 阿宇.mp3",
    img_file: "十一年（翻自 邱永传） - 阿宇.webp",
    lyrics_file: "十一年（翻自 邱永传） - 阿宇.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "阿宇",
    time: "04:08",
    des: "2011年，那年大一，这个调调成了永远的痛。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "山海",
    song_file: "山海《完整版》cover(草东没有派对） - 万豹.mp3",
    img_file: "山海《完整版》cover(草东没有派对） - 万豹.jpg",
    lyrics_file: "山海《完整版》cover(草东没有派对） - 万豹.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "万豹",
    time: "04:08",
    des: "我们都太胆小了\n民国时不敢做军阀\n乱世里不敢去起义\n太平盛世不敢说我爱你",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "十一种孤独",
    song_file: "十一种孤独 - 宿羽阳.mp3",
    img_file: "十一种孤独 - 宿羽阳.webp",
    lyrics_file: "十一种孤独 - 宿羽阳.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "宿羽阳",
    time: "04:41",
    des: "如果一个人住，千万不要在下午睡午觉，一觉睡到六七点，等你一睁开眼，看着朦胧黑黑的天空和空荡的房间，会有一种被全世界遗弃的感觉，孤独在这一刻体现的淋漓尽致。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "漠河舞厅·2022",
    song_file: "漠河舞厅·2022 - 柳爽.mp3",
    img_file: "漠河舞厅·2022 - 柳爽.jpg",
    lyrics_file: "漠河舞厅·2022 - 柳爽.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "柳爽",
    time: "05:04",
    des: "\"人类用什么衡量爱?\"\n \"用分开后的痛苦.\"",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "无期",
    song_file: "无期-石白其.mp3",
    img_file: "无期-石白其.webp",
    lyrics_file: "无期-石白其.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "石白其",
    time: "02:40",
    des: "我喜欢你",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "真爱的力量",
    song_file: "真爱的力量 - Maj7_Music 巴音孟克.mp3",
    img_file: "真爱的力量 - Maj7_Music 巴音孟克.webp",
    lyrics_file: "真爱的力量 - Maj7_Music 巴音孟克.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Maj7_Music 巴音孟克",
    time: "03:59",
    des: "真爱最动人的地方，是让普通人也有了对抗世界的勇气。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "the lake heard everything",
    song_file: "the lake heard everything - Paper Blush.mp3",
    img_file: "the lake heard everything - Paper Blush.jpg",
    lyrics_file: "the lake heard everything - Paper Blush.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Paper Blush",
    time: "02:39",
    des: "湖面什么都没说，却像替所有沉默的人保存了秘密。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "悬日",
    song_file: "悬日 - 田馥甄.mp3",
    img_file: "悬日 - 田馥甄.jpg",
    lyrics_file: "悬日 - 田馥甄.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "田馥甄",
    time: "04:31",
    des: "有些人已经离开了你的生活，但还没有离开你的时间。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "第四十二街来信——记稚楚《悬日》",
    song_file: "第四十二街来信——记稚楚《悬日》 - 绕指柔_.mp3",
    img_file: "第四十二街来信——记稚楚《悬日》 - 绕指柔_.jpg",
    lyrics_file: "第四十二街来信——记稚楚《悬日》 - 绕指柔_.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "绕指柔",
    time: "03:59",
    des: "太阳明明高悬天空，却似乎永远无法真正落下。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "你走",
    song_file: "你走 - 李宗锦（松紧先生）.mp3",
    img_file: "你走 - 李宗锦（松紧先生）.jpg",
    lyrics_file: "你走 - 李宗锦（松紧先生）.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李宗锦（松紧先生）",
    time: "04:04",
    des: "你走以后，房间没有变空，是我突然不知道该往哪里放想念。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "BINGBIAN病变 (女声版)",
    song_file: "BINGBIAN病变 (女声版) - 鞠文娴.mp3",
    img_file: "BINGBIAN病变 (女声版) - 鞠文娴.jpg",
    lyrics_file: "BINGBIAN病变 (女声版) - 鞠文娴.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "鞠文娴",
    time: "04:07",
    des: "你要搞清楚，是你喜欢对方，不是人家喜欢你。\n既然你动心了，主动了，就算受了天大的委屈，也是预料中的事，怪不得任何人。你不是小朋友了，不开心不会死，结果只能自己承担，不管多难过，你也只能自己熬。\n谁叫你有本事喜欢人家，没本事让人家喜欢你呢。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "泸沽湖（烟嗓女声版）",
    song_file: "泸沽湖（烟嗓女声版） - 陈惟.mp3",
    img_file: "泸沽湖（烟嗓女声版） - 陈惟.jpg",
    lyrics_file: "泸沽湖（烟嗓女声版） - 陈惟.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈惟",
    time: "03:37",
    des: "湖水和烟嗓一起起雾，像把远方唱成一场旧梦。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "斯琴高丽的伤心",
    song_file: "斯琴高丽的伤心 - Yichen9247.mp3",
    img_file: "斯琴高丽的伤心 - Yichen9247.jpg",
    lyrics_file: "斯琴高丽的伤心 - Yichen9247.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Yichen9247",
    time: "03:52",
    des: "有些歌一开口就很旧，像那些说不清的委屈，终于被人替你唱了出来。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "醉清风",
    song_file: "醉清风 - 弦子.mp3",
    img_file: "醉清风 - 弦子.jpg",
    lyrics_file: "醉清风 - 弦子.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "弦子",
    time: "05:07",
    des: "且听清风拂过。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "有彩虹",
    song_file: "有彩虹.mp3",
    img_file: "有彩虹.webp",
    lyrics_file: "有彩虹.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "빈센트 블루 (Vincent Blue)",
    time: "03:23",
    des: "谢谢你， 听尽了我不堪的人生， 仍选择站在我这边。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "ありがとう（泪的告白）",
    song_file: "arigatou - kokia.mp3",
    img_file: "arigatou - kokia.jpg",
    lyrics_file: "arigatou - kokia.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "kokia",
    time: "04:08",
    des: "遇见的都是幸运，或许下次见面真的只能靠运气了。然而我几乎不出门啊",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "丁香花 (2007版) ",
    song_file: "丁香花 (2007版) - 唐磊.mp3",
    img_file: "丁香花 (2007版) - 唐磊.jpg",
    lyrics_file: "丁香花 (2007版) - 唐磊.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "唐磊",
    time: "04:25",
    des: "我再也没有见到过你，再也见不到了。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "一生所爱",
    song_file: "一生所爱 - 卢冠廷,莫文蔚.mp3",
    img_file: "一生所爱 - 卢冠廷,莫文蔚.jpg",
    lyrics_file: "一生所爱 - 卢冠廷,莫文蔚.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "卢冠廷,莫文蔚",
    time: "04:33",
    des: "她的手只有我的手四分之三那么大，可我还是没能抓住。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "清新的小女孩 (For Ma)",
    song_file: "清新的小女孩 (For Ma) - July Tun.mp3",
    img_file: "清新的小女孩 (For Ma) - July Tun.jpg",
    lyrics_file: "清新的小女孩 (For Ma) - July Tun.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "July Tun",
    time: "04:01",
    des: "也许永远都不可能懂，但不影响她很好听。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "The Sound Of Silence",
    song_file: "The Sound Of Silence - Simon & Garfunkel.mp3",
    img_file: "The Sound Of Silence - Simon & Garfunkel.jpg",
    lyrics_file: "The Sound Of Silence - Simon & Garfunkel.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Simon & Garfunkel",
    time: "03:04",
    des: "当我独自走在路上，在街道的灯光笼罩下，我看见人头攒动，有的人在说着无聊的话，有的人在听着别人说着无聊的话。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "假如爱有天意 (Live)",
    song_file: "假如爱有天意 (Live) - 李健.mp3",
    img_file: "假如爱有天意 (Live) - 李健.jpg",
    lyrics_file: "假如爱有天意 (Live) - 李健.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "李健",
    time: "05:03",
    des: "我们真的愿意为一个人变成更好的自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "灰色空间",
    song_file: "灰色空间 - 罗志祥.mp3",
    img_file: "灰色空间 - 罗志祥.jpg",
    lyrics_file: "灰色空间 - 罗志祥.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "罗志祥",
    time: "03:57",
    des: "灰色空间我是谁",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "后来",
    song_file: "后来-刘若英.MP3",
    img_file: "后来-刘若英.jpg",
    lyrics_file: "后来-刘若英.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "刘若英",
    time: "05:41",
    des: "我曾经以为你会一直在，后来才知道，有的人走了就是走了。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "我用什么把你留住",
    song_file: "我用什么把你留住-福禄寿.MP3",
    img_file: "我用什么把你留住-福禄寿.jpg",
    lyrics_file: "我用什么把你留住-福禄寿.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "福禄寿",
    time: "05:29",
    des: "我问过自己很多次：如果我再努力一点，你会不会留下？可惜答案永远都是沉默。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "求佛",
    song_file: "求佛 - 誓言.mp3",
    img_file: "求佛 - 誓言.jpg",
    lyrics_file: "求佛 - 誓言.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "誓言",
    time: "04:46",
    des: "求佛，求佛，求佛。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "犯错",
    song_file: "犯错 - 顾峰.mp3",
    img_file: "犯错 - 顾峰.jpg",
    lyrics_file: "犯错 - 顾峰.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "顾峰",
    time: "03:16",
    des: "后来才明白，最难原谅的不是对方，是当时太用力的自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "好想爱这个世界啊",
    song_file: "好想爱这个世界啊 - 华晨宇.mp3",
    img_file: "好想爱这个世界啊 - 华晨宇.jpg",
    lyrics_file: "好想爱这个世界啊 - 华晨宇.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "华晨宇",
    time: "04:18",
    des: "这首歌像一句很轻的拥抱：你已经做得很好了。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "三生石下",
    song_file: "三生石下 - 大欢.mp3",
    img_file: "三生石下 - 大欢.webp",
    lyrics_file: "三生石下 - 大欢.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "大欢",
    time: "04:23",
    des: "有些缘分像旧誓言，明知荒唐，却还是让人红了眼眶。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "拯救",
    song_file: "拯救 - 孙楠.mp3",
    img_file: "拯救 - 孙楠.webp",
    lyrics_file: "拯救 - 孙楠.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "孙楠",
    time: "05:32",
    des: "每个快撑不住的夜晚，都希望有人听见那句无声的求救。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "凉凉",
    song_file: "凉凉 - 杨宗纬.mp3",
    img_file: "凉凉 - 杨宗纬.webp",
    lyrics_file: "凉凉 - 杨宗纬.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "杨宗纬",
    time: "05:33",
    des: "最凉的不是结局，是明明还爱着，却只能把名字放回风里。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "再次见到你",
    song_file: "再次见到你 _Once Again（翻自 Mad Clown&金娜英） - 阿YueYue.mp3",
    img_file: "再次见到你 _Once Again（翻自 Mad Clown&金娜英） - 阿YueYue.jpg",
    lyrics_file: "再次见到你 _Once Again（翻自 Mad Clown&金娜英） - 阿YueYue.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "阿YueYue",
    time: "03:56",
    des: "有些重逢只适合在歌里发生，现实里我们连问候都怕太用力。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "她",
    song_file: "她 - 不可撤销乐队.mp3",
    img_file: "她 - 不可撤销乐队.jpg",
    lyrics_file: "她 - 不可撤销乐队.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "不可撤销乐队",
    time: "04:31",
    des: "有些名字不能轻易提起，一提起，整段青春都会回头。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "盛夏的果实",
    song_file: "盛夏的果实 - 莫文蔚.mp3",
    img_file: "盛夏的果实 - 莫文蔚.jpg",
    lyrics_file: "盛夏的果实 - 莫文蔚.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "莫文蔚",
    time: "04:10",
    des: "成年后再听才懂，成熟原来是把遗憾唱得云淡风轻。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "我的歌声里",
    song_file: "我的歌声里-曲婉婷.mp3",
    img_file: "我的歌声里-曲婉婷.jpg",
    lyrics_file: "我的歌声里-曲婉婷.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "曲婉婷",
    time: "03:36",
    des: "最心酸的不是忘不掉，而是突然在街角听到这首歌时，一秒就想起你。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "越长大越孤单",
    song_file: "越长大越孤单 - 牛奶咖啡.mp3",
    img_file: "越长大越孤单 - 牛奶咖啡.jpg",
    lyrics_file: "越长大越孤单 - 牛奶咖啡.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "牛奶咖啡",
    time: "04:28",
    des: "小时候害怕黑暗，长大后害怕沉默。越长大，越发现能说真话的人越来越少。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "空白格",
    song_file: "空白格 - 杨宗纬.mp3",
    img_file: "空白格 - 杨宗纬.jpg",
    lyrics_file: "空白格 - 杨宗纬.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "杨宗纬",
    time: "03:38",
    des: "我以为我会是最坚强的那一个，我还是高估了自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "丫头",
    song_file: "丫头 - 王童语.mp3",
    img_file: "丫头 - 王童语.webp",
    lyrics_file: "丫头 - 王童语.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "王童语",
    time: "05:32",
    des: "最朴素的情话，往往最像一个人认真爱过的样子。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "十年",
    song_file: "十年 - 陈奕迅.mp3",
    img_file: "十年 - 陈奕迅.jpg",
    lyrics_file: "十年 - 陈奕迅.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "陈奕迅",
    time: "03:25",
    des: "有几个十年呢？",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "我好像在哪见过你",
    song_file: "我好像在哪见过你 - 薛之谦.mp3",
    img_file: "我好像在哪见过你 - 薛之谦.jpg",
    lyrics_file: "我好像在哪见过你 - 薛之谦.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "薛之谦",
    time: "04:39",
    des: "有些熟悉感没有来处，却像命运在回忆里轻轻敲门。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "童话",
    song_file: "童话 - 光良.mp3",
    img_file: "童话 - 光良.jpg",
    lyrics_file: "童话 - 光良.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "光良",
    time: "04:04",
    des: "长大后再听童话，才懂相信本身就是很勇敢的事。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "遇见",
    song_file: "遇见 - 孙燕姿.mp3",
    img_file: "遇见 - 孙燕姿.jpg",
    lyrics_file: "遇见 - 孙燕姿.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "孙燕姿",
    time: "03:29",
    des: "最好的相遇常常没有预告，却能把整段人生悄悄改写。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "她说",
    song_file: "她说 - 林俊杰.mp3",
    img_file: "她说 - 林俊杰.jpg",
    lyrics_file: "她说 - 林俊杰.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "林俊杰",
    time: "05:20",
    des: "她说的每一句都像雨后的独白，温柔里藏着没说完的疼。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "僕が死のうと思ったのは",
    song_file: "boku-ga-shinou-to-omotta-no-wa - mika-nakashima.mp3",
    img_file: "boku-ga-shinou-to-omotta-no-wa - mika-nakashima.jpg",
    lyrics_file: "boku-ga-shinou-to-omotta-no-wa - mika-nakashima.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "中島美嘉",
    time: "06:22",
    des: "这首歌把最深的低谷唱成一道微光，沉重却仍让人想活下去。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "心做し",
    song_file: "心做し - majiko.mp3",
    img_file: "心做し - majiko.jpg",
    lyrics_file: "心做し - majiko.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "majiko",
    time: "04:33",
    des: "像把心捧出来问世界，为什么越想靠近越疼。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHANGGANZHIYU,
    song_name: "放生",
    song_file: "放生 - 范逸臣.mp3",
    img_file: "放生 - 范逸臣.jpg",
    lyrics_file: "放生 - 范逸臣.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "范逸臣",
    time: "04:31",
    des: "爱到最后才懂，放过彼此有时也是最后的温柔。",
  }
];
