import { CONFIG } from '../app/config.js';

const TYPE = "史诗配乐";
const FILE_MUSIC_SHISHIPEIYUE = "shishipeiyue/";

export const epicScoreList = [
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "亡灵序曲 (The Dawn)",
    song_file: "The Dawn_亡灵序曲.mp3",
    img_file: "The Dawn_亡灵序曲.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Dreamtale",
    time: "04:06",
    des: "《The Dawn》的原意为黎明、拂晓、破晓，但在国内网络上，广被讹传为\"亡灵序曲\"。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "伊卡洛斯 Icarus",
    song_file: "icarus.mp3",
    img_file: "icarus.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Ivan Torrent",
    time: "04:35",
    des: "Ivan Torrent 是西班牙一个独立作曲家和制作人。为流行音乐和舞蹈艺术家在西班牙工作多年，作为一个设计师，也为广播电台做广告宣传和广告歌曲。现在Ivan Torrent想更专注于电影音乐的场景，为预告片音乐公司工作，以及做演示样品库。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Heart of Courage",
    song_file: "Heart of Courage - Two Steps From Hell.mp3",
    img_file: "Heart of Courage - Two Steps From Hell.jpg",
    lyrics_file: "Heart of Courage - Two Steps From Hell.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Two Steps From Hell",
    time: "01:57",
    des: "真正的勇气不是不害怕，而是害怕的时候还愿意往前一步。",
  },
    {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Victory",
    song_file: "Victory (Orchestral) - Two Steps From Hell.mp3",
    img_file: "Victory (Orchestral) - Two Steps From Hell.jpg",
    lyrics_file: "Victory (Orchestral) - Two Steps From Hell.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Two Steps From Hell",
    time: "05:22",
    des: "这首一响，连失败过的自己都想重新站起来一次。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Time",
    song_file: "Time - Hans Zimmer.mp3",
    img_file: "Time - Hans Zimmer.jpg",
    lyrics_file: "Time - Hans Zimmer.lrc",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_file,
    author: "Hans Zimmer",
    time: "04:35",
    des: "时间最温柔也最残忍，它带走很多东西，也留下我们成为现在的自己。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Breath and Life",
    song_file: "Breath And Life - Audiomachine.mp3",
    img_file: "Breath And Life - Audiomachine.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Audiomachine",
    time: "01:48",
    des: "像第一束光穿过云层，提醒人活着本身就是一场盛大的远行。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Electric Romeo",
    song_file: "Electric Romeo - Immediate Music.mp3",
    img_file: "Electric Romeo - Immediate Music.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Immediate Music",
    time: "02:28",
    des: "浪漫被鼓点点燃，像一场明知危险却仍要奔赴的梦。",
  },
  {
    song_type: TYPE,
    song_path: FILE_MUSIC_SHISHIPEIYUE,
    song_name: "Experience - Ludovico Einaudi",
    song_file: "Experience - Ludovico Einaudi.mp3",
    img_file: "Experience - Ludovico Einaudi.jpg",
    lyrics_type: CONFIG.LOAD_LYRICS_TYPE.TYPE_chunyinyue,
    author: "Ludovico Einaudi",
    time: "05:16",
    des: "越安静的旋律越有力量，它不推你流泪，只陪你把情绪走完。",
  }
];
